/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.zabalburu.daw1.aplicaciontorneo.vista.vista.dialogs;

import javax.swing.JOptionPane;
import org.zabalburu.daw1.aplicaciontorneo.modelo.Juego;
import org.zabalburu.daw1.aplicaciontorneo.servicio.TorneoServicio;

/**
 *
 * @author DAW1
 */
public class DlgJugador extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgJugador.class.getName());

    private Juego juego;
    private TorneoServicio servicio = TorneoServicio.getServicio();

    /**
     * Creates new form DlgJuego
     */
    public DlgJugador(java.awt.Frame parent, boolean modal, Juego juego) {
        super(parent, modal);
        this.juego = juego;
        initComponents();
        mostrar();
    }

    private void mostrar() {
        if (juego != null) {
            lblId.setText(String.valueOf(juego.getId()));
            txtTitulo.setText(juego.getTitulo());
            txaDescripcion.setText(juego.getDescripcion());
            cbxTipo.setSelectedItem(juego.getTipo());
            lblTituloForm.setText("Editando - " + juego.getTitulo());
            this.setTitle("Editando - " + juego.getTitulo());
        } else {
            lblId.setText("Nuevo");
            lblTituloForm.setText("Nuevo Juego");
            this.setTitle("Nuevo");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblTituloForm = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        lblLabelId = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblLabelTitulo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jspDescripcion = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        lblLabelTipo = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        lblImagen = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        pnlAcciones = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloForm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblTituloForm.setText("Juego");
        pnlTitulo.add(lblTituloForm);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        pnlDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        lblLabelId.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblLabelId.setText("ID");

        lblId.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblId.setText("jLabel2");

        lblLabelTitulo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblLabelTitulo.setText("Título:");

        lblDescripcion.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblDescripcion.setText("Descripción");

        txaDescripcion.setColumns(20);
        txaDescripcion.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txaDescripcion.setRows(5);
        jspDescripcion.setViewportView(txaDescripcion);

        lblLabelTipo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblLabelTipo.setText("Tipo:");

        cbxTipo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOBA", "Tactical Shooter", "Sports", "Board Game", "Fighting", "Hero Shooter", "Battle Royale", "RTS", "Racing", "Card Game", "Auto-Battler", "MOBA Mobile", "Action Mobile", "Adventure", "Strategy Mobile", "Arena Brawler", "Arena Shooter", "Hybrid Shooter", "Sports Brawler", "RPG", "Sandbox" }));

        lblImagen.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/daw1/aplicaciontorneo/imagenes/addimage.png"))); // NOI18N
        lblImagen.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLabelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlDatosLayout.createSequentialGroup()
                                    .addComponent(lblLabelTipo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jspDescripcion))
                            .addComponent(lblDescripcion))
                        .addGap(18, 18, 18)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLabelId)
                        .addComponent(lblId))
                    .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLabelTitulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLabelTipo)
                            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jspDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(pnlDatos, java.awt.BorderLayout.CENTER);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlAcciones.add(btnCancelar);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlAcciones.add(btnGuardar);

        getContentPane().add(pnlAcciones, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtTitulo.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "El título es OBLIGATORIO", "Falta Título", JOptionPane.ERROR_MESSAGE);
            //txtTitulo.putClientProperty("JComponent.outline", "error"); 
        } else {
            if (juego == null) {
                juego = new Juego();
            }
            juego.setTitulo(txtTitulo.getText());
            juego.setTipo(cbxTipo.getSelectedItem().toString());
            juego.setDescripcion(txaDescripcion.getText());
            if (lblId.getText().equalsIgnoreCase("nuevo")) {
                servicio.addJuego(juego);
            } else {
                servicio.modifyJuego(juego);
            }
            JOptionPane.showMessageDialog(this, "Datos registrados correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgJugador dialog = new DlgJugador(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JScrollPane jspDescripcion;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblLabelId;
    private javax.swing.JLabel lblLabelTipo;
    private javax.swing.JLabel lblLabelTitulo;
    private javax.swing.JLabel lblTituloForm;
    private javax.swing.JPanel pnlAcciones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextArea txaDescripcion;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

}
