/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.zabalburu.daw1.aplicaciontorneo.vista.vista.dialogs;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.zabalburu.daw1.aplicaciontorneo.modelo.Juego;
import org.zabalburu.daw1.aplicaciontorneo.modelo.Jugador;
import org.zabalburu.daw1.aplicaciontorneo.servicio.TorneoServicio;
import org.zabalburu.daw1.aplicaciontorneo.util.CircleImage;

/**
 *
 * @author DAW1
 */
public class DlgJugador extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgJugador.class.getName());

    private Jugador jugador;
    private ImageIcon imagenSeleccionada;
    private TorneoServicio servicio = TorneoServicio.getServicio();

    /**
     * Creates new form DlgJuego
     */
    public DlgJugador(java.awt.Frame parent, boolean modal, Jugador jugador) {
        super(parent, modal);
        this.jugador = jugador;
        initComponents();
        lblImagen.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lblImagen.setToolTipText("Cargar Imagen");
        lblImagen.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                abrirFileChooser();
            }

            private void abrirFileChooser() {
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setDialogTitle("Seleccionar imagen");
                FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imágenes (PNG)", "png");
                fileChooser.setFileFilter(filtro);
                fileChooser.setAcceptAllFileFilterUsed(false);
                fileChooser.setMultiSelectionEnabled(false);
                int resultado = fileChooser.showOpenDialog(null);
                if (resultado == JFileChooser.APPROVE_OPTION) {
                    File archivoSeleccionado = fileChooser.getSelectedFile();
                    cargarImagenImportada(archivoSeleccionado);
                }
            }

            private void cargarImagenImportada(File archivo) {
                ImageIcon iconoOriginal = new ImageIcon(archivo.getAbsolutePath());
                imagenSeleccionada = iconoOriginal;
                Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
                lblImagen.setIcon(new ImageIcon(imagenEscalada));
            }
        });
        mostrar();
    }

    private void mostrar() {
        if (jugador != null) {
            lblId.setText(String.valueOf(jugador.getId()));
            txtNick.setText(jugador.getNick());
            txtNombre.setText(jugador.getNombre());
            txtApellidos.setText(jugador.getApellidos());
            lblTituloForm.setText("Editando - " + jugador.getNick());
            lblImagen.setIcon(jugador.getImagenNormal());
            this.setTitle("Editando - " + jugador.getNick());
        } else {
            lblId.setText("Nuevo");
            lblTituloForm.setText("Nuevo Jugador");
            this.setTitle("Nuevo");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblTituloForm = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        lblLabelId = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblNick = new javax.swing.JLabel();
        txtNick = new javax.swing.JTextField();
        pnlAcciones = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloForm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblTituloForm.setText("Jugador");
        pnlTitulo.add(lblTituloForm);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        pnlDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        lblLabelId.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblLabelId.setText("ID");

        lblId.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblId.setText("jLabel2");

        lblNombre.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        lblImagen.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/daw1/aplicaciontorneo/iconos/imagen_normal.png"))); // NOI18N
        lblImagen.setPreferredSize(new java.awt.Dimension(150, 150));

        lblApellidos.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblApellidos.setText("Apellidos:");

        lblNick.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblNick.setText("Nick:");

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblApellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblLabelId)
                        .addGap(18, 18, 18)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNick, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabelId)
                    .addComponent(lblId)
                    .addComponent(txtNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNick))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidos))
                .addGap(28, 28, 28))
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(pnlDatos, java.awt.BorderLayout.CENTER);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlAcciones.add(btnCancelar);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlAcciones.add(btnGuardar);

        getContentPane().add(pnlAcciones, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtNick.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "El Nick es OBLIGATORIO", "Error", JOptionPane.ERROR_MESSAGE);
            //txtTitulo.putClientProperty("JComponent.outline", "error"); 
        } else if (txtNombre.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "El Nombre es OBLIGATORIO", "Error", JOptionPane.ERROR_MESSAGE);
            //txtTitulo.putClientProperty("JComponent.outline", "error"); 
        } else if (txtApellidos.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Los Apellidos son OBLIGATORIOS", "Error", JOptionPane.ERROR_MESSAGE);
            //txtTitulo.putClientProperty("JComponent.outline", "error"); 
        } else {
            if (jugador == null) {
                jugador = new Jugador();
            }
            jugador.setNick(txtNick.getText());
            jugador.setNombre(txtNombre.getText());
            jugador.setApellidos(txtApellidos.getText());
            if (imagenSeleccionada != null) {
                BufferedImage bff = toBufferedImage(imagenSeleccionada);
                String ruta = Jugador.DIR_PRINCIPAL + jugador.getNick() + ".png";
                try {
                    ImageIO.write(bff, "PNG", new File(ruta)); // Escribimos
                    jugador.setImagen(ruta); // Asignamos la ruta y CARGAMOS NORMAL Y AVATAR APARTIR DE LA RUTA
                    jugador.setImagenesNormalAvatar();
                    imagenSeleccionada = null;
                } catch (IOException ex) {
                    System.getLogger(DlgJugador.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            } else {
                jugador.setImagen("");
            }
            if (lblId.getText().equalsIgnoreCase("nuevo")) {
                servicio.addJugador(jugador);
            } else {
                servicio.modifyJugador(jugador);
            }
            JOptionPane.showMessageDialog(this, "Datos registrados correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgJugador dialog = new DlgJugador(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblLabelId;
    private javax.swing.JLabel lblNick;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTituloForm;
    private javax.swing.JPanel pnlAcciones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtNick;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    public BufferedImage toBufferedImage(ImageIcon icon) {
        // 1. Creamos un BufferedImage con el mismo ancho y alto que el icono
        BufferedImage bi = new BufferedImage(
                icon.getIconWidth(),
                icon.getIconHeight(),
                BufferedImage.TYPE_INT_ARGB // Soporta transparencia
        );

        // 2. Obtenemos el contexto gráfico (el "pincel")
        Graphics g = bi.createGraphics();

        // 3. Pintamos el icono en el BufferedImage
        icon.paintIcon(null, g, 0, 0);

        // 4. Liberamos recursos
        g.dispose();

        return bi;
    }
}
