/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.daw1.prueba_habitacionreserva_1.vista;

import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.zabalburu.daw1.prueba_habitacionreserva_1.modelo.Habitacion;
import org.zabalburu.daw1.prueba_habitacionreserva_1.modelo.Reserva;
import org.zabalburu.daw1.prueba_habitacionreserva_1.servicio.HotelServicio;
import org.zabalburu.daw1.prueba_habitacionreserva_1.util.CargarHabitaciones;
import org.zabalburu.daw1.prueba_habitacionreserva_1.util.EstadoApp;
import org.zabalburu.daw1.prueba_habitacionreserva_1.util.EstadoReserva;
import org.zabalburu.daw1.prueba_habitacionreserva_1.util.TipoHabitacion;

/**
 *
 * @author Iker Navarro Pérez
 */
public class HabitacionFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HabitacionFrame.class.getName());

    private static HotelServicio servicio = HotelServicio.getInstance();
    EstadoApp estado = EstadoApp.CONSULTA;
    CargarHabitaciones cargaHabitacionesSeleccionada = CargarHabitaciones.CARGAR_TODAS_LAS_HABITACIONES;
    int pos = 0; //En la posición en la que estamos.
    private List<Habitacion> habitaciones = servicio.getHabitaciones();
    private NumberFormat nfMoneda = NumberFormat.getCurrencyInstance();
    private Vector<String> vctTitulosTabla = new Vector<>();

    /**
     * Creates new form HabitacionFrame
     */
    public HabitacionFrame() {
        initComponents();
        vctTitulosTabla.add("ID Reserva");
        vctTitulosTabla.add("Estado");
        vctTitulosTabla.add("Cliente");
        vctTitulosTabla.add("Fecha Entrada");
        vctTitulosTabla.add("Fecha Salida");
        vctTitulosTabla.add("Importe");
        vctTitulosTabla.add("ID Habitación");
        this.setLocationRelativeTo(null);
        cargarTipoHabitacion();
        cargarFiltrarEstadoReserva();
        cbxFiltrarEstadoReserva.setSelectedIndex(3);
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrimero = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        lblPosicion = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jspReservas = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNroHabitacion = new javax.swing.JTextField();
        lblNroHabitacion = new javax.swing.JLabel();
        lblPrecioNoche = new javax.swing.JLabel();
        lblTipoHabitacion = new javax.swing.JLabel();
        lblEstadoHabitacion = new javax.swing.JLabel();
        ftxPrecioNoche = new javax.swing.JFormattedTextField();
        btnCargarTodasHabitaciones = new javax.swing.JButton();
        btnCargarHabitacionesDisponibles = new javax.swing.JButton();
        txtEstadoHabitacion = new javax.swing.JTextField();
        btnGestionarReservas = new javax.swing.JButton();
        cbxTipoHabitacion = new javax.swing.JComboBox<>();
        lblFiltrarEstadosReservas = new javax.swing.JLabel();
        cbxFiltrarEstadoReserva = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPrimero.setText("|<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        lblPosicion.setText("[ 0 / 1 ]");

        lblTitulo.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblTitulo.setText("Gestión Habitaciones");

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspReservas.setViewportView(tblReservas);

        lblId.setText("ID");

        lblNroHabitacion.setText("Número de Habitación");

        lblPrecioNoche.setText("Precio / Noche");

        lblTipoHabitacion.setText("Tipo de Habitación");

        lblEstadoHabitacion.setText("Estado");

        btnCargarTodasHabitaciones.setText("Cargar Habitaciones [ TODAS ]");
        btnCargarTodasHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTodasHabitacionesActionPerformed(evt);
            }
        });

        btnCargarHabitacionesDisponibles.setText("Cargar Habitaciones [ DISPONIBLES ]");
        btnCargarHabitacionesDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarHabitacionesDisponiblesActionPerformed(evt);
            }
        });

        btnGestionarReservas.setText("Gestionar Reservas");
        btnGestionarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarReservasActionPerformed(evt);
            }
        });

        lblFiltrarEstadosReservas.setText("Filtrar Estados Reservas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblFiltrarEstadosReservas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxFiltrarEstadoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(249, 249, 249))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jspReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCargarTodasHabitaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCargarHabitacionesDisponibles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblTipoHabitacion)
                                .addComponent(ftxPrecioNoche, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPrecioNoche)
                                .addComponent(btnGestionarReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(cbxTipoHabitacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNroHabitacion)
                                        .addComponent(lblId)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEstadoHabitacion)
                                        .addComponent(txtEstadoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblPosicion)
                        .addGap(12, 12, 12)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblFiltrarEstadosReservas)
                    .addComponent(cbxFiltrarEstadoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCargarTodasHabitaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCargarHabitacionesDisponibles)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(lblEstadoHabitacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstadoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(lblNroHabitacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lblPrecioNoche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxPrecioNoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTipoHabitacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGestionarReservas)
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadir)
                    .addComponent(btnModificar)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnEliminar)
                    .addComponent(btnPrimero)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente)
                    .addComponent(btnUltimo)
                    .addComponent(lblPosicion))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        pos = 0;
        mostrar();
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        pos--;
        mostrar();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        pos++;
        mostrar();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        pos = habitaciones.size() - 1;
        mostrar();
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnCargarTodasHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarTodasHabitacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarTodasHabitacionesActionPerformed

    private void btnCargarHabitacionesDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarHabitacionesDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarHabitacionesDisponiblesActionPerformed

    private void btnGestionarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarReservasActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        estado = EstadoApp.ALTA;
        mostrar();
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        estado = EstadoApp.MODIFICACION;
        mostrar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        estado = EstadoApp.CONSULTA;
        mostrar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HabitacionFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargarHabitacionesDisponibles;
    private javax.swing.JButton btnCargarTodasHabitaciones;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGestionarReservas;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox<EstadoReserva> cbxFiltrarEstadoReserva;
    private javax.swing.JComboBox<TipoHabitacion> cbxTipoHabitacion;
    private javax.swing.JFormattedTextField ftxPrecioNoche;
    private javax.swing.JScrollPane jspReservas;
    private javax.swing.JLabel lblEstadoHabitacion;
    private javax.swing.JLabel lblFiltrarEstadosReservas;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNroHabitacion;
    private javax.swing.JLabel lblPosicion;
    private javax.swing.JLabel lblPrecioNoche;
    private javax.swing.JLabel lblTipoHabitacion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtEstadoHabitacion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNroHabitacion;
    // End of variables declaration//GEN-END:variables

    private void mostrar() {
        cargarHabitaciones(cargaHabitacionesSeleccionada);
        if (habitaciones.isEmpty()) {
            estado = EstadoApp.ALTA;
            pos = 0;
        }
        if (estado == EstadoApp.ALTA) {
            lblPosicion.setText("Nuevo");
            txtId.setText(" | Automático | ");
            txtEstadoHabitacion.setText("[NO DISPONIBLE]");
            txtNroHabitacion.setText("");
            ftxPrecioNoche.setText("");
            cbxTipoHabitacion.setSelectedIndex(0);
        } else {
            Habitacion habitacion = habitaciones.get(pos);
            txtId.setText(habitacion.getId().toString());
            boolean habitacionDisponible = habitacion.getReservas().stream()
                    .noneMatch(r -> r.getEstado().equals(EstadoReserva.PENDIENTE));
            txtEstadoHabitacion.setText(habitacionDisponible ? "Disponible" : "NO Disponible");
            txtNroHabitacion.setText(habitacion.getNumHabitacion().toString());
            ftxPrecioNoche.setText(habitacion.getPrecioNoche().toString());
            cbxTipoHabitacion.setSelectedItem(habitacion.getTipo());
            lblPosicion.setText("%02d / %02d".formatted(pos + 1, habitaciones.size()));
        }
        btnAnterior.setEnabled(pos > 0 && estado == EstadoApp.CONSULTA);
        btnPrimero.setEnabled(pos > 0 && estado == EstadoApp.CONSULTA);
        btnSiguiente.setEnabled(pos < habitaciones.size() - 1 && estado == EstadoApp.CONSULTA);
        btnUltimo.setEnabled(pos < habitaciones.size() - 1 && estado == EstadoApp.CONSULTA);
        btnCancelar.setEnabled(estado != EstadoApp.CONSULTA && habitaciones.size() > 0);
        btnGuardar.setEnabled(estado != EstadoApp.CONSULTA);
        btnModificar.setEnabled(estado == EstadoApp.CONSULTA);
        btnAñadir.setEnabled(estado == EstadoApp.CONSULTA);
        btnEliminar.setEnabled(estado == EstadoApp.CONSULTA);
        btnGestionarReservas.setEnabled(estado == EstadoApp.CONSULTA);
        cbxFiltrarEstadoReserva.setEnabled(estado == EstadoApp.CONSULTA);
        btnCargarTodasHabitaciones.setEnabled(estado == EstadoApp.CONSULTA);
        btnCargarHabitacionesDisponibles.setEnabled(estado == EstadoApp.CONSULTA);
        txtId.setEnabled(false);
        txtEstadoHabitacion.setEnabled(false);
        txtNroHabitacion.setEnabled(estado != EstadoApp.CONSULTA);
        ftxPrecioNoche.setEnabled(estado != EstadoApp.CONSULTA);
        cbxTipoHabitacion.setEnabled(estado != EstadoApp.CONSULTA);
        if (estado == EstadoApp.ALTA) {
            DefaultTableModel dtmModelo = (DefaultTableModel) tblReservas.getModel();
            dtmModelo.setDataVector(null, vctTitulosTabla);
        } else {
            cargarReservas(null);
        }

    }

    private void cargarTipoHabitacion() {
        cbxTipoHabitacion.addItem(TipoHabitacion.INDIVIDUAL);
        cbxTipoHabitacion.addItem(TipoHabitacion.DOBLE);
        cbxTipoHabitacion.addItem(TipoHabitacion.SUITE);
    }

    private void cargarFiltrarEstadoReserva() {
        cbxFiltrarEstadoReserva.addItem(null); // PARA MOSTRAR LAS RESERVAS DE LA PROPIA HABITACIÓN
        cbxFiltrarEstadoReserva.addItem(EstadoReserva.CANCELADA);
        cbxFiltrarEstadoReserva.addItem(EstadoReserva.COMPLETADA);
        cbxFiltrarEstadoReserva.addItem(EstadoReserva.PENDIENTE);
    }

    private List<Habitacion> cargarHabitaciones(CargarHabitaciones tipoCarga) {
        if (tipoCarga == CargarHabitaciones.CARGAR_TODAS_LAS_HABITACIONES) {
            habitaciones = servicio.getHabitaciones();
        } else {
            habitaciones = servicio.getHabitacionesDisponibles();
        }
        return habitaciones;
    }

    private void cargarReservas(EstadoReserva estado) {
        List<Reserva> listReservas = new ArrayList<>();
        if (estado != null) {
            listReservas = servicio.getReservasEstado(estado);
        } else {
            listReservas = servicio.getHabitaciones().get(pos).getReservas();
        }
        Vector<Vector<String>> vctDatos = new Vector<>();
        for (Reserva r : listReservas) {
            vctDatos.add(añadirFilaReserva(r));
        }
        DefaultTableModel dtmModelo = (DefaultTableModel) tblReservas.getModel();
        dtmModelo.setDataVector(vctDatos, vctTitulosTabla);
    }

    private Vector<String> añadirFilaReserva(Reserva r) {
        Vector<String> vctFilaTabla = new Vector<>();
        vctFilaTabla.add(r.getId().toString());
        vctFilaTabla.add(r.getEstado().toString());
        vctFilaTabla.add(r.getNombreCliente());
        vctFilaTabla.add(r.getFechaEntrada().format(DateTimeFormatter.ISO_DATE));
        vctFilaTabla.add(r.getFechaSalida().format(DateTimeFormatter.ISO_DATE));
        vctFilaTabla.add(nfMoneda.format(r.getImporteTotal()));
        vctFilaTabla.add(r.getHabitacion().getId().toString());
        return vctFilaTabla;
    }
}
