/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.gestionmantenimientosjpa.view;

import java.awt.Component;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.zabalburu.gestionmantenimientosjpa.model.Maquina;
import org.zabalburu.gestionmantenimientosjpa.model.Revision;
import org.zabalburu.gestionmantenimientosjpa.model.Tecnico;
import org.zabalburu.gestionmantenimientosjpa.service.MantenimientoService;
import org.zabalburu.gestionmantenimientosjpa.util.DateConversion;

/**
 *
 * @author Iker Navarro Pérez
 */
public class MantenimientoView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantenimientoView.class.getName());
    private MantenimientoService service = MantenimientoService.getService();

    /**
     * Creates new form MantenimientoView
     */
    public MantenimientoView() {
        initComponents();
        inicializarTabla();
        inicializarComboTecnicos();
        cbxTecnicos.addItemListener((e) -> {
            actualizarDatos();
        });
        cbxMaquinas.addItemListener((e) -> {
            cargarTabla();
        });
        ftxTotalCoste.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlNorte = new javax.swing.JPanel();
        lblTecnico = new javax.swing.JLabel();
        cbxTecnicos = new javax.swing.JComboBox<>();
        lblMaquina = new javax.swing.JLabel();
        cbxMaquinas = new javax.swing.JComboBox<>();
        lblFecha = new javax.swing.JLabel();
        ftxFecha = new javax.swing.JFormattedTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblCoste = new javax.swing.JLabel();
        ftxCoste = new javax.swing.JFormattedTextField();
        pnlCentro = new javax.swing.JPanel();
        jspDatos = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        pnlSur = new javax.swing.JPanel();
        lblTotalCoste = new javax.swing.JLabel();
        ftxTotalCoste = new javax.swing.JFormattedTextField();
        fllSeparador = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnAñadirRevisión = new javax.swing.JButton();
        btnEliminarRevisión = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Mantenimientos");
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlNorte.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15), javax.swing.BorderFactory.createTitledBorder("Datos de la Revisión")));
        pnlNorte.setPreferredSize(new java.awt.Dimension(800, 250));
        pnlNorte.setLayout(new java.awt.GridBagLayout());

        lblTecnico.setText("Técnico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 2);
        pnlNorte.add(lblTecnico, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 2);
        pnlNorte.add(cbxTecnicos, gridBagConstraints);

        lblMaquina.setText("Máquina:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 2);
        pnlNorte.add(lblMaquina, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 2);
        pnlNorte.add(cbxMaquinas, gridBagConstraints);

        lblFecha.setText("Fecha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 2);
        pnlNorte.add(lblFecha, gridBagConstraints);

        ftxFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 2);
        pnlNorte.add(ftxFecha, gridBagConstraints);

        lblDescripcion.setText("Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 2);
        pnlNorte.add(lblDescripcion, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 2);
        pnlNorte.add(txtDescripcion, gridBagConstraints);

        lblCoste.setText("Coste:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 2);
        pnlNorte.add(lblCoste, gridBagConstraints);

        ftxCoste.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 2);
        pnlNorte.add(ftxCoste, gridBagConstraints);

        getContentPane().add(pnlNorte, java.awt.BorderLayout.NORTH);

        pnlCentro.setPreferredSize(new java.awt.Dimension(800, 450));
        pnlCentro.setLayout(new java.awt.GridBagLayout());

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspDatos.setViewportView(tblDatos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        pnlCentro.add(jspDatos, gridBagConstraints);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlSur.setPreferredSize(new java.awt.Dimension(800, 100));
        pnlSur.setLayout(new java.awt.GridBagLayout());

        lblTotalCoste.setText("Total Coste:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSur.add(lblTotalCoste, gridBagConstraints);

        ftxTotalCoste.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSur.add(ftxTotalCoste, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        pnlSur.add(fllSeparador, gridBagConstraints);

        btnAñadirRevisión.setText("Añadir Revisión");
        btnAñadirRevisión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirRevisiónActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSur.add(btnAñadirRevisión, gridBagConstraints);

        btnEliminarRevisión.setText("Eliminar Revisión");
        btnEliminarRevisión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRevisiónActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSur.add(btnEliminarRevisión, gridBagConstraints);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSur.add(btnSalir, gridBagConstraints);

        getContentPane().add(pnlSur, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAñadirRevisiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirRevisiónActionPerformed
        if (!txtDescripcion.getText().isBlank()) {
            Revision r = new Revision();

            /*1*/
            r.setMaquina((Maquina) cbxMaquinas.getSelectedItem());

            /*2*/
            if (!ftxFecha.getText().isBlank()) {
                r.setFecha(DateConversion.fromDate((Date) ftxFecha.getValue()));
            } else {
                r.setFecha(LocalDate.now());
            }

            /*3*/
            r.setDescripcion(txtDescripcion.getText());

            /*4*/
            if (!ftxCoste.getText().isBlank()) {
                r.setCoste(Double.valueOf((ftxCoste.getText().replace(",", "."))));
            } else {
                r.setCoste(0.0);
            }

            try {
                service.nuevaRevision(r);
                JOptionPane.showMessageDialog(this, "Revisión registrada correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
                cargarTabla();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo descripción está vacío!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAñadirRevisiónActionPerformed

    private void btnEliminarRevisiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRevisiónActionPerformed

        if (tblDatos.getSelectedRow() != -1) {
            Integer idRevisionSeleccionada = (Integer) tblDatos.getModel().getValueAt(tblDatos.getSelectedRow(), 0);
            if (JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar la revisión con [ ID : %d ] ?".formatted(idRevisionSeleccionada), "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                service.eliminarRevision(idRevisionSeleccionada);
                JOptionPane.showMessageDialog(this, "Revisión eliminada correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
                cargarTabla();
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay ninguna revisión seleccionada para eliminar!", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarRevisiónActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MantenimientoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirRevisión;
    private javax.swing.JButton btnEliminarRevisión;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Maquina> cbxMaquinas;
    private javax.swing.JComboBox<Tecnico> cbxTecnicos;
    private javax.swing.Box.Filler fllSeparador;
    private javax.swing.JFormattedTextField ftxCoste;
    private javax.swing.JFormattedTextField ftxFecha;
    private javax.swing.JFormattedTextField ftxTotalCoste;
    private javax.swing.JScrollPane jspDatos;
    private javax.swing.JLabel lblCoste;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMaquina;
    private javax.swing.JLabel lblTecnico;
    private javax.swing.JLabel lblTotalCoste;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlSur;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables

    private void inicializarComboTecnicos() {
        cbxTecnicos.removeAllItems();
        for (Tecnico t : service.getTecnicos()) {
            cbxTecnicos.addItem(t);
        }
        actualizarDatos();
        cargarTabla();
    }

    private void actualizarDatos() {
        Tecnico t = (Tecnico) cbxTecnicos.getSelectedItem();
        if (t != null) {
            t = service.getTecnicoConMaquinas(t.getId());
            cargarComboMaquinas(t);
        }
    }

    private void cargarComboMaquinas(Tecnico t) {
        cbxMaquinas.removeAllItems();
        for (Maquina m : t.getMaquinas()
                .stream()
                .sorted((m1, m2) -> m1.getNombre().compareTo(m2.getNombre()))
                .toList()) {
            cbxMaquinas.addItem(m);
        }
    }

    private void cargarTabla() {
        Maquina m = (Maquina) cbxMaquinas.getSelectedItem();
        if (m != null) {

            m = service.getMaquina(m.getId());
            List<Revision> revisionesOrdenadas = m.getRevisiones().stream()
                    .sorted((r1, r2) -> r2.getFecha().compareTo(r1.getFecha()))
                    .toList();

            DefaultTableModel dtm = (DefaultTableModel) tblDatos.getModel();
            dtm.setRowCount(0);

            for (Revision r : revisionesOrdenadas) {
                Vector vctFila = new Vector();
                vctFila.add(r.getId());
                vctFila.add(r.getFecha());
                vctFila.add(r.getDescripcion());
                vctFila.add(r.getCoste());
                dtm.addRow(vctFila);
            }
            actualizarContadorTotalCostes(revisionesOrdenadas);
        }
    }

    private void inicializarTabla() {
        tblDatos.setModel(new DefaultTableModel(new String[]{
            "ID",
            "Fecha",
            "Descripción",
            "Coste"
        }, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return switch (columnIndex) {
                    case 0 ->
                        Integer.class;
                    case 1 ->
                        LocalDate.class;
                    case 3 ->
                        Double.class;
                    default ->
                        String.class;
                };
            }
        });

        tblDatos.setDefaultRenderer(LocalDate.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel lbl = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                LocalDate ld = (LocalDate) value;
                lbl.setHorizontalAlignment(JLabel.CENTER);
                return lbl;
            }
        });

        tblDatos.setDefaultRenderer(Double.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel lbl = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                Double d = (Double) value;
                lbl.setText(d + " €");
                lbl.setHorizontalAlignment(JLabel.CENTER);
                return lbl;
            }
        });

        tblDatos.setDefaultRenderer(Integer.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel lbl = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                Integer i = (Integer) value;
                lbl.setHorizontalAlignment(JLabel.CENTER);
                return lbl;
            }
        });

        tblDatos.setDefaultRenderer(String.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel lbl = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                String s = (String) value;
                lbl.setHorizontalAlignment(JLabel.CENTER);
                return lbl;
            }
        });
    }

    private void actualizarContadorTotalCostes(List<Revision> revisionesOrdenadas) {
        Double total = 0.0;
        for (Revision r : revisionesOrdenadas) {
            total += r.getCoste();
        }
        ftxTotalCoste.setValue(total);
    }
}
