/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.daw1.pruebaobj_trimestre2.vista;

import java.text.NumberFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.zabalburu.daw1.pruebaobj_trimestre2.modelo.Cliente;
import org.zabalburu.daw1.pruebaobj_trimestre2.modelo.Pedido;
import org.zabalburu.daw1.pruebaobj_trimestre2.servicio.TiendaServicio;
import org.zabalburu.daw1.pruebaobj_trimestre2.util.Estado;

/**
 *
 * @author Iker Navarro Pérz
 */
public class ClienteFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteFrame.class.getName());

    private static TiendaServicio servicio = TiendaServicio.getInstance();
    Estado estado = Estado.CONSULTA;
    int pos = 0; //En la posición que estamos.
    private List<Cliente> clientes = servicio.getClientes();
    private NumberFormat nfMoneda = NumberFormat.getCurrencyInstance();
    private Vector<String> vctTitulosTabla = new Vector<>();

    /**
     * Creates new form ClienteFrame
     */
    public ClienteFrame() {
        initComponents();
        vctTitulosTabla.add("ID");
        vctTitulosTabla.add("Fecha");
        vctTitulosTabla.add("Descripción");
        vctTitulosTabla.add("Cantidad");
        vctTitulosTabla.add("Precio");
        vctTitulosTabla.add("Total");
        vctTitulosTabla.add("Pagado");
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jspPedidos = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        ftxImporteTotalPedidosCliente = new javax.swing.JFormattedTextField();
        btnPagarPedido = new javax.swing.JButton();
        btnAñadirPedido = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        lblContadorPos = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPedidos = new javax.swing.JLabel();
        ftxTelefono = new javax.swing.JFormattedTextField();
        btnEliminarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Gestión de Clientes");

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspPedidos.setViewportView(tblPedidos);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        ftxImporteTotalPedidosCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftxImporteTotalPedidosCliente.setText("0 €");
        ftxImporteTotalPedidosCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnPagarPedido.setText("Pagar Pedido");
        btnPagarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarPedidoActionPerformed(evt);
            }
        });

        btnAñadirPedido.setText("Añadir Pedido");
        btnAñadirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirPedidoActionPerformed(evt);
            }
        });

        btnPrimero.setText("|<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        lblContadorPos.setText("Nuevo");

        lblId.setText("ID");

        txtId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblNombre.setText("Nombre");

        lblTelefono.setText("Telefono");

        lblEmail.setText("Email");

        lblPedidos.setText("Pedidos");

        ftxTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btnEliminarPedido.setText("Eliminar Pedido");
        btnEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(356, 356, 356))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPedidos)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPagarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAñadirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblContadorPos)
                                .addGap(18, 18, 18)
                                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ftxImporteTotalPedidosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftxTelefono))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtEmail)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jspPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxImporteTotalPedidosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagarPedido)
                    .addComponent(btnAñadirPedido)
                    .addComponent(btnPrimero)
                    .addComponent(btnAnterior)
                    .addComponent(btnUltimo)
                    .addComponent(btnSiguiente)
                    .addComponent(lblContadorPos)
                    .addComponent(btnEliminarPedido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnModificar)
                    .addComponent(btnNuevo))
                .addGap(11, 11, 11))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        pos = 0;
        mostrar();
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        estado = Estado.ALTA;
        mostrar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        estado = Estado.MODIFICACION;
        mostrar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        estado = Estado.CONSULTA;
        mostrar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        pos--;
        mostrar();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        pos++;
        mostrar();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        pos = clientes.size() - 1;
        mostrar();
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Eliminar el Cliente: { %s [ ID: %d ]}".formatted(clientes.get(pos).getNombre(), clientes.get(pos).getId()), "Eliminar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                servicio.removeCliente(clientes.get(pos).getId());
                JOptionPane.showMessageDialog(this, "El cliente ha sido eliminado de manera satisfactoria!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "<html><h3>¡No ha sido posible eliminar el cliente!</h3><br /> ¡El cliente tiene pagos pendientes!</html>", "Error", JOptionPane.ERROR_MESSAGE);
            }
            clientes = servicio.getClientes();
            if (pos == clientes.size()) {
                pos--;
            }
            mostrar();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Cliente c = new Cliente();
        if (estado == Estado.MODIFICACION) {
            c.setId(clientes.get(pos).getId());
            c.setPedidos(clientes.get(pos).getPedidos());
        }
        if (txtNombre.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "El Nombre es OBLIGATORIO!", "Error", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
        } else if (txtEmail.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "El Email es OBLIGATORIO!", "Error", JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocus();
        } else if (ftxTelefono.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "El Número de Telefono es OBLIGATORIO!", "Error", JOptionPane.ERROR_MESSAGE);
            ftxTelefono.requestFocus();
        } else {
            c.setNombre(txtNombre.getText());
            c.setEmail(txtEmail.getText());
            c.setTelefono(ftxTelefono.getText());
            if (estado == Estado.ALTA) {
                servicio.addCliente(c);
                JOptionPane.showMessageDialog(this, "El cliente ha sido registrado de manera satisfactoria!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                servicio.modifyCliente(c);
                JOptionPane.showMessageDialog(this, "El cliente ha sido modificado de manera satisfactoria!", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
            clientes = servicio.getClientes();
            pos = clientes.indexOf(c);
            estado = Estado.CONSULTA;
            mostrar();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPedidoActionPerformed
        int filaSeleccionada = tblPedidos.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar el pedido que desee ELIMINAR",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            // Al no tener un método en el dao tenemos que garantizar la bidireccionaldiad.
            Cliente c = clientes.get(pos);
            Pedido eliminar = c.getPedidos().get(filaSeleccionada);
            if (eliminar.isPagado()) {
                servicio.getPedidos().remove(eliminar);
                c.getPedidos().remove(eliminar);
                servicio.modifyCliente(c);
            } else {
                JOptionPane.showMessageDialog(this, "El pedido está PENDIENTE DE PAGO!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            clientes = servicio.getClientes();
            mostrar();
        }
    }//GEN-LAST:event_btnEliminarPedidoActionPerformed

    private void btnPagarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarPedidoActionPerformed
        int filaSeleccionada = tblPedidos.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar el pedido que desee PAGAR",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            Cliente c = clientes.get(pos);
            Pedido pagar = c.getPedidos().get(filaSeleccionada);
            if (!pagar.isPagado()) {
                servicio.pagarPedido(pagar.getId());
                int posPedido = c.getPedidos().indexOf(pagar);
                c.getPedidos().set(posPedido, pagar);
                servicio.modifyCliente(c);
                JOptionPane.showMessageDialog(this, "El %s  ha sido pagado satisfactoriamente!".formatted(pagar), "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "El pedido YA está PAGADO!", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
            clientes = servicio.getClientes();
            mostrar();
        }
    }//GEN-LAST:event_btnPagarPedidoActionPerformed

    private void btnAñadirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirPedidoActionPerformed
        new PedidoFrame(this,true,clientes.get(pos)).setVisible(true);
        clientes = servicio.getClientes();
        mostrar();
    }//GEN-LAST:event_btnAñadirPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnAñadirPedido;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarPedido;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPagarPedido;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JFormattedTextField ftxImporteTotalPedidosCliente;
    private javax.swing.JFormattedTextField ftxTelefono;
    private javax.swing.JScrollPane jspPedidos;
    private javax.swing.JLabel lblContadorPos;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPedidos;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void mostrar() {
        if (clientes.isEmpty()) {
            estado = Estado.ALTA;
            pos = 0;
        }
        if (estado == Estado.ALTA) {
            lblContadorPos.setText("Nuevo");
            txtId.setText(" | Automático | ");
            ftxImporteTotalPedidosCliente.setText("0 €");
            txtNombre.setText("");
            txtEmail.setText("");
            ftxTelefono.setText("");
        } else {
            Cliente c = clientes.get(pos);
            txtId.setText(String.valueOf(c.getId()));
            ftxImporteTotalPedidosCliente.setText(nfMoneda.format(Double.valueOf(c.getImporteTotal())));
            txtNombre.setText(c.getNombre());
            txtEmail.setText(c.getEmail());
            ftxTelefono.setText(c.getTelefono());
            lblContadorPos.setText("%02d / %02d".formatted(pos + 1, clientes.size()));
        }
        btnAnterior.setEnabled(pos > 0 && estado == Estado.CONSULTA);
        btnPrimero.setEnabled(pos > 0 && estado == Estado.CONSULTA);
        btnSiguiente.setEnabled(pos < clientes.size() - 1 && estado == Estado.CONSULTA);
        btnUltimo.setEnabled(pos < clientes.size() - 1 && estado == Estado.CONSULTA);
        btnCancelar.setEnabled(estado != Estado.CONSULTA && clientes.size() > 0);
        btnGuardar.setEnabled(estado != Estado.CONSULTA);
        btnModificar.setEnabled(estado == Estado.CONSULTA);
        btnNuevo.setEnabled(estado == Estado.CONSULTA);
        btnEliminar.setEnabled(estado == Estado.CONSULTA);
        btnAñadirPedido.setEnabled(estado == Estado.CONSULTA);
        btnEliminarPedido.setEnabled(estado == Estado.CONSULTA);
        btnPagarPedido.setEnabled(estado == Estado.CONSULTA);
        txtId.setEnabled(false);
        ftxImporteTotalPedidosCliente.setEnabled(false);
        txtNombre.setEnabled(estado != Estado.CONSULTA);
        txtEmail.setEnabled(estado != Estado.CONSULTA);
        ftxTelefono.setEnabled(estado != Estado.CONSULTA);
        if (estado == Estado.ALTA) {
            DefaultTableModel dtmModelo = (DefaultTableModel) tblPedidos.getModel();
            dtmModelo.setDataVector(null, vctTitulosTabla);
        } else {
            cargarPedidos();
        }
    }

    private void cargarPedidos() {
        Vector<Vector<String>> vctDatos = new Vector<>();
        for (Pedido p : clientes.get(pos).getPedidos()) {
            Vector<String> vctFilaTabla = new Vector<>();
            vctFilaTabla.add(p.getId().toString());
            vctFilaTabla.add(p.getFechaPedido().toString());
            vctFilaTabla.add(p.getDescripcion());
            vctFilaTabla.add(String.valueOf(p.getCantidad()));
            vctFilaTabla.add(nfMoneda.format(p.getPrecioUnitario()));
            vctFilaTabla.add(nfMoneda.format(p.getImporte()));
            vctFilaTabla.add(p.isPagado() ? "Si" : "No");
            vctDatos.add(vctFilaTabla);
        }
        DefaultTableModel dtmModelo = (DefaultTableModel) tblPedidos.getModel();
        dtmModelo.setDataVector(vctDatos, vctTitulosTabla);
    }
}
