/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.daw1.pruebajpa.views;

import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.zabalburu.daw1.pruebajpa.model.Usuario;
import org.zabalburu.daw1.pruebajpa.servicio.TareasServicio;

/**
 *
 * @author ichueca
 */
public class FrmTareas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmTareas.class.getName());

    private static TareasServicio servicio = TareasServicio.getServicio();
    
    /**
     * Creates new form FrmTareas
     */
    public FrmTareas() {
        initComponents();
        crearTablaUsuarios();
        cargarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jspUsuarios = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        tbrUsuarios = new javax.swing.JToolBar();
        btnNuevoUsuario = new javax.swing.JButton();
        btnModificarUsuartio = new javax.swing.JButton();
        btnDetallesUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        mbrUsuarios = new javax.swing.JMenuBar();
        mnuUsuarios = new javax.swing.JMenu();
        mniNuevo = new javax.swing.JMenuItem();
        mniModificar = new javax.swing.JMenuItem();
        mniEliminar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniDetalles = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tareas");

        pnlDatos.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("Gestión de Tareas");
        pnlTitulo.add(lblTitulo);

        pnlDatos.add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlBotones.add(btnSalir);

        pnlDatos.add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        tblUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jspUsuarios.setViewportView(tblUsuarios);

        pnlDatos.add(jspUsuarios, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.CENTER);

        tbrUsuarios.setRollover(true);

        btnNuevoUsuario.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnNuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/daw1/pruebajpa/images/Plus.png"))); // NOI18N
        btnNuevoUsuario.setFocusable(false);
        btnNuevoUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioActionPerformed(evt);
            }
        });
        tbrUsuarios.add(btnNuevoUsuario);

        btnModificarUsuartio.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnModificarUsuartio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/daw1/pruebajpa/images/Edit.png"))); // NOI18N
        btnModificarUsuartio.setFocusable(false);
        btnModificarUsuartio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarUsuartio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificarUsuartio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUsuartioActionPerformed(evt);
            }
        });
        tbrUsuarios.add(btnModificarUsuartio);

        btnDetallesUsuario.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnDetallesUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/daw1/pruebajpa/images/Document.png"))); // NOI18N
        btnDetallesUsuario.setFocusable(false);
        btnDetallesUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDetallesUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrUsuarios.add(btnDetallesUsuario);

        btnEliminarUsuario.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/daw1/pruebajpa/images/Trash.png"))); // NOI18N
        btnEliminarUsuario.setFocusable(false);
        btnEliminarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrUsuarios.add(btnEliminarUsuario);

        getContentPane().add(tbrUsuarios, java.awt.BorderLayout.PAGE_START);

        mnuUsuarios.setMnemonic('u');
        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mniNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/daw1/pruebajpa/images/Plus.png"))); // NOI18N
        mniNuevo.setMnemonic('n');
        mniNuevo.setText("Nuevo");
        mniNuevo.setToolTipText("");
        mniNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNuevoActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mniNuevo);

        mniModificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/daw1/pruebajpa/images/Edit.png"))); // NOI18N
        mniModificar.setMnemonic('m');
        mniModificar.setText("Modificar");
        mniModificar.setToolTipText("");
        mniModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniModificarActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mniModificar);

        mniEliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        mniEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/daw1/pruebajpa/images/Trash.png"))); // NOI18N
        mniEliminar.setMnemonic('e');
        mniEliminar.setText("Eliminar");
        mniEliminar.setToolTipText("");
        mnuUsuarios.add(mniEliminar);
        mnuUsuarios.add(jSeparator1);

        mniDetalles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDetalles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/daw1/pruebajpa/images/Document.png"))); // NOI18N
        mniDetalles.setMnemonic('v');
        mniDetalles.setText("Ver Detalles");
        mniDetalles.setToolTipText("");
        mnuUsuarios.add(mniDetalles);

        mbrUsuarios.add(mnuUsuarios);

        jMenu2.setText("Salir");
        mbrUsuarios.add(jMenu2);

        setJMenuBar(mbrUsuarios);

        setSize(new java.awt.Dimension(559, 380));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void mniNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNuevoActionPerformed
        nuevoUsuario();
    }//GEN-LAST:event_mniNuevoActionPerformed

    private void btnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioActionPerformed
        nuevoUsuario();
    }//GEN-LAST:event_btnNuevoUsuarioActionPerformed

    private void mniModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniModificarActionPerformed
        modificarUsuario();
    }//GEN-LAST:event_mniModificarActionPerformed

    private void btnModificarUsuartioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUsuartioActionPerformed
        modificarUsuario();
    }//GEN-LAST:event_btnModificarUsuartioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmTareas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetallesUsuario;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnModificarUsuartio;
    private javax.swing.JButton btnNuevoUsuario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JScrollPane jspUsuarios;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuBar mbrUsuarios;
    private javax.swing.JMenuItem mniDetalles;
    private javax.swing.JMenuItem mniEliminar;
    private javax.swing.JMenuItem mniModificar;
    private javax.swing.JMenuItem mniNuevo;
    private javax.swing.JMenu mnuUsuarios;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JToolBar tbrUsuarios;
    // End of variables declaration//GEN-END:variables

    private void crearTablaUsuarios() {
        tblUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblUsuarios.setModel(new DefaultTableModel(
            // Títulos
            new String[]{
                "Id",
                "Nombre"
            },
            //Nº Filas
            0){
            @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            
        });
    }

    private void cargarUsuarios() {
        DefaultTableModel modelo = (DefaultTableModel) tblUsuarios.getModel();
        modelo.setRowCount(0); // Truncar los datos actuales de la tabla
        for(Usuario u : servicio.getUsuarios()){
            modelo.addRow(new Object[]{
                u.getId(),
                u.getNombre() + " " + u.getApellidos()
            });
        }
    }

    private void nuevoUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void modificarUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
