/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.daw1.guiada_almacenproductos_1.vista;

import java.text.NumberFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.zabalburu.daw1.guiada_almacenproductos_1.modelo.Almacen;
import org.zabalburu.daw1.guiada_almacenproductos_1.modelo.Producto;
import org.zabalburu.daw1.guiada_almacenproductos_1.servicio.InventarioServicio;
import org.zabalburu.daw1.guiada_almacenproductos_1.util.Estado;
import org.zabalburu.daw1.guiada_almacenproductos_1.util.Tabla;

/**
 *
 * @author Iker Navarro Pérez
 */
public class FrameAlmacen extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameAlmacen.class.getName());

    private static InventarioServicio servicio = InventarioServicio.getInstance();
    Estado estado = Estado.CONSULTA;
    int pos = 0; //En que posición estamos.
    private List<Almacen> almacenes = servicio.getAlmacenes();
    private NumberFormat nfMoneda = NumberFormat.getCurrencyInstance();
    private Vector<String> vctTitulosTabla = new Vector<>();

    /**
     * Creates new form FrameInventario
     */
    public FrameAlmacen() {
        initComponents();
        vctTitulosTabla.add("ID");
        vctTitulosTabla.add("Nombre");
        vctTitulosTabla.add("Código");
        vctTitulosTabla.add("Cantidad");
        vctTitulosTabla.add("ID_Almacén");
        vctTitulosTabla.add("Precio");
        this.setLocationRelativeTo(null);
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        btnPrimero = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        lblContadorAlmacenes = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        lblUbicacion = new javax.swing.JLabel();
        lblCapacidadMaxima = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCapacidadMaxima = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jspProductos = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        fxtValorTotalInventario = new javax.swing.JFormattedTextField();
        btnNuevoProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        lblContadorTotalProductos = new javax.swing.JLabel();
        btnMostrarMax = new javax.swing.JButton();
        btnMostrarMin = new javax.swing.JButton();

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPrimero.setText("|<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        lblContadorAlmacenes.setText("[0/0]");

        lblId.setText("ID");

        lblNombre.setText("Nombre");

        txtUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUbicacionActionPerformed(evt);
            }
        });

        lblUbicacion.setText("Ubicación");

        lblCapacidadMaxima.setText("Capacidad Máxima");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtCapacidadMaxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadMaximaActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspProductos.setViewportView(tblProductos);

        lblTitulo.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblTitulo.setText("Gestión Almacenes");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        fxtValorTotalInventario.setText("€0");

        btnNuevoProducto.setText("Nuevo Producto");
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });

        btnEliminarProducto.setText("Eliminar Producto");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        lblContadorTotalProductos.setText("Total Productos: 0");

        btnMostrarMax.setText("Mostrar € Max");
        btnMostrarMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMaxActionPerformed(evt);
            }
        });

        btnMostrarMin.setText("Mostrar € Min");
        btnMostrarMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevoProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fxtValorTotalInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jspProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMostrarMin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMostrarMax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblContadorTotalProductos)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUbicacion)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblId)
                                    .addComponent(lblNombre))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCapacidadMaxima)
                                .addGap(18, 18, 18)
                                .addComponent(txtCapacidadMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContadorAlmacenes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContadorTotalProductos)
                    .addComponent(btnMostrarMax)
                    .addComponent(btnMostrarMin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUbicacion)
                            .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCapacidadMaxima)
                            .addComponent(txtCapacidadMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jspProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fxtValorTotalInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoProducto)
                    .addComponent(btnEliminarProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrimero)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAnterior)
                    .addComponent(btnUltimo)
                    .addComponent(lblContadorAlmacenes)
                    .addComponent(btnNuevo)
                    .addComponent(btnModificar)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        pos = 0;
        mostrar();
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        pos++;
        mostrar();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        pos--;
        mostrar();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        pos = almacenes.size() - 1;
        mostrar();
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void txtUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUbicacionActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtCapacidadMaximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadMaximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadMaximaActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        estado = Estado.ALTA;
        mostrar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        estado = Estado.MODIFICACION;
        mostrar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        estado = Estado.CONSULTA;
        mostrar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Eliminar el Almacén: { %s [ ID: %d ]}".formatted(almacenes.get(pos).getNombre(), almacenes.get(pos).getId()), "Eliminar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            servicio.removeAlmacen(almacenes.get(pos).getId());
            almacenes = servicio.getAlmacenes();
            if (pos == almacenes.size()) {
                pos--;
            }
            mostrar();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Almacen a = new Almacen();
        if (estado == Estado.MODIFICACION) {
            a.setId(almacenes.get(pos).getId());
        }
        if (txtNombre.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "El Nombre es OBLIGATORIO!", "Error", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
        } else if (txtUbicacion.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "La Ubicación es OBLIGATORIA!", "Error", JOptionPane.ERROR_MESSAGE);
            txtUbicacion.requestFocus();
        } else if (txtCapacidadMaxima.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "La Capacidad Máxima es OBLIGATORIA!", "Error", JOptionPane.ERROR_MESSAGE);
            txtCapacidadMaxima.requestFocus();
        } else {
            a.setNombre(txtNombre.getText());
            a.setUbicacion(txtUbicacion.getText());
            try {
                a.setCapacidadMaxima(Integer.parseInt(txtCapacidadMaxima.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Formato NO VÁLIDO en Capacidad Máxima! Por defecto: 100", "Error", JOptionPane.ERROR_MESSAGE);
                a.setCapacidadMaxima(100);
            }
            if (estado == Estado.ALTA) {
                servicio.addAlmacen(a);
            } else {
                servicio.modifyAlmacen(a);
            }
            almacenes = servicio.getAlmacenes();
            pos = almacenes.indexOf(a);
            estado = Estado.CONSULTA;
            mostrar();
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        new FrameProducto(this, true, almacenes.get(pos)).setVisible(true);
        almacenes = servicio.getAlmacenes();
        mostrar();
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        int filaSeleccionada = tblProductos.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar el Producto que desee ELIMINAR",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            Producto eliminar = almacenes.get(pos).getProductos().get(filaSeleccionada);
            servicio.removeProducto(eliminar.getId());
            almacenes = servicio.getAlmacenes();
            mostrar();
        }
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnMostrarMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMaxActionPerformed
        cargarProductos(Tabla.CARGAR_PRECIO_MAX);
    }//GEN-LAST:event_btnMostrarMaxActionPerformed

    private void btnMostrarMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMinActionPerformed
        cargarProductos(Tabla.CARGAR_PRECIO_MIN);
    }//GEN-LAST:event_btnMostrarMinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameAlmacen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrarMax;
    private javax.swing.JButton btnMostrarMin;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JFormattedTextField fxtValorTotalInventario;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JScrollPane jspProductos;
    private javax.swing.JLabel lblCapacidadMaxima;
    private javax.swing.JLabel lblContadorAlmacenes;
    private javax.swing.JLabel lblContadorTotalProductos;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCapacidadMaxima;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables

    private void mostrar() {
        if (almacenes.isEmpty()) {
            estado = Estado.ALTA;
            pos = 0;
        }
        if (estado == Estado.ALTA) {
            lblContadorAlmacenes.setText("Nuevo");
            txtId.setText(" | Automático | ");
            fxtValorTotalInventario.setText("0 €");
            lblContadorTotalProductos.setText("Total Productos: 0");
            txtNombre.setText("");
            txtUbicacion.setText("");
            txtCapacidadMaxima.setText("");

        } else {
            Almacen almacen = almacenes.get(pos);
            txtId.setText(almacen.getId().toString());
            txtNombre.setText(almacen.getNombre());
            txtUbicacion.setText(almacen.getUbicacion());
            txtCapacidadMaxima.setText(almacen.getCapacidadMaxima().toString());
            lblContadorAlmacenes.setText("%02d / %02d".formatted(pos + 1, almacenes.size()));
        }
        btnAnterior.setEnabled(pos > 0 && estado == Estado.CONSULTA);
        btnPrimero.setEnabled(pos > 0 && estado == Estado.CONSULTA);
        btnSiguiente.setEnabled(pos < almacenes.size() - 1 && estado == Estado.CONSULTA);
        btnUltimo.setEnabled(pos < almacenes.size() - 1 && estado == Estado.CONSULTA);
        btnCancelar.setEnabled(estado != Estado.CONSULTA && almacenes.size() > 0);
        btnGuardar.setEnabled(estado != Estado.CONSULTA);
        btnModificar.setEnabled(estado == Estado.CONSULTA);
        btnNuevo.setEnabled(estado == Estado.CONSULTA);
        btnEliminar.setEnabled(estado == Estado.CONSULTA);
        btnNuevoProducto.setEnabled(estado == Estado.CONSULTA);
        btnEliminarProducto.setEnabled(estado == Estado.CONSULTA);
        btnMostrarMax.setEnabled(estado == Estado.CONSULTA);
        btnMostrarMin.setEnabled(estado == Estado.CONSULTA);
        txtId.setEnabled(false);
        txtNombre.setEnabled(estado != Estado.CONSULTA);
        txtUbicacion.setEnabled(estado != Estado.CONSULTA);
        txtCapacidadMaxima.setEnabled(estado != Estado.CONSULTA);
        fxtValorTotalInventario.setEnabled(false);
        if (estado == Estado.ALTA) {
            DefaultTableModel dtmModelo = (DefaultTableModel) tblProductos.getModel();
            dtmModelo.setDataVector(null, vctTitulosTabla);
        } else {
            cargarProductos(Tabla.CARGAR_TODOS_LOS_PRODUCTOS);
        }

    }

    private void cargarProductos(Tabla tipoCarga) {
        Vector<Vector<String>> vctDatos = new Vector<>();
        Double totalInventario = 0.0;
        Integer contadorProductos = 0;
        boolean errorCarga = false;
        if (tipoCarga == Tabla.CARGAR_TODOS_LOS_PRODUCTOS) {
            for (Producto p : almacenes.get(pos).getProductos()) {
                vctDatos.add(añadirFilaProducto(p));
                totalInventario += p.getPrecio() * p.getCantidad();
                contadorProductos++;
            }
        }
        if (tipoCarga == Tabla.CARGAR_PRECIO_MIN) {
            try {
                Double precioMin = Double.parseDouble(JOptionPane.showInputDialog(this, "Introduzca el Precio Mínimo: ", "0.0"));
                for (Producto p : servicio.getProductosPrecioMin(precioMin)) {
                    vctDatos.add(añadirFilaProducto(p));
                    totalInventario += p.getPrecio() * p.getCantidad();
                    contadorProductos++;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Introduzca una cantidad VÁLIDA!", "Error", JOptionPane.ERROR_MESSAGE);
                errorCarga = true;
            }
        }
        if (tipoCarga == Tabla.CARGAR_PRECIO_MAX) {
            try {
                Double precioMax = Double.parseDouble(JOptionPane.showInputDialog(this, "Introduzca el Precio Máximo: ", "0.0"));
                for (Producto p : servicio.getProductosPrecioMax(precioMax)) {
                    vctDatos.add(añadirFilaProducto(p));
                    totalInventario += p.getPrecio() * p.getCantidad();
                    contadorProductos++;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Introduzca una cantidad VÁLIDA!", "Error", JOptionPane.ERROR_MESSAGE);
                errorCarga = true;
            }
        }
        lblContadorTotalProductos.setText("Total Productos: %d".formatted(contadorProductos));
        fxtValorTotalInventario.setValue(nfMoneda.format(totalInventario));
        DefaultTableModel dtmModelo = (DefaultTableModel) tblProductos.getModel();
        dtmModelo.setDataVector(vctDatos, vctTitulosTabla);
        if (errorCarga) {
            cargarProductos(Tabla.CARGAR_TODOS_LOS_PRODUCTOS);
        }
    }

    private Vector<String> añadirFilaProducto(Producto p) {
        Vector<String> vctFilaTabla = new Vector<>();
        vctFilaTabla.add(p.getId().toString());
        vctFilaTabla.add(p.getNombre());
        vctFilaTabla.add(p.getCodigo());
        vctFilaTabla.add(p.getCantidad().toString());
        vctFilaTabla.add(p.getAlmacen().getId().toString());
        vctFilaTabla.add(nfMoneda.format(p.getPrecio()));
        return vctFilaTabla;
    }
}
