/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.zabalburu.daw1.aplicaciontorneo.vista.paneles;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.driver.utils.WalletLocation;
import org.zabalburu.daw1.aplicaciontorneo.modelo.Juego;
import org.zabalburu.daw1.aplicaciontorneo.modelo.Jugador;
import org.zabalburu.daw1.aplicaciontorneo.modelo.Partida;
import org.zabalburu.daw1.aplicaciontorneo.servicio.TorneoServicio;
import org.zabalburu.daw1.aplicaciontorneo.util.InicializarDatos;

/**
 *
 * @author DAW1
 */
public class PnlPartidas extends javax.swing.JPanel {

    private static TorneoServicio servicio = TorneoServicio.getServicio();

    /**
     * Creates new form PnlPartida
     */
    public PnlPartidas() {
        initComponents();
        inicializarTabla();
        inicializarCBX();
        cargarJuegosCBX();
        mostrarPartidas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlSuperior = new javax.swing.JPanel();
        lblJugadores = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnRefrescar = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        lblJuego = new javax.swing.JLabel();
        cbxJuego = new javax.swing.JComboBox<>();
        lblJugador = new javax.swing.JLabel();
        cbxJugador = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jspPartidas = new javax.swing.JScrollPane();
        tblPartidas = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout());

        pnlSuperior.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 5, 0));
        pnlSuperior.setLayout(new javax.swing.BoxLayout(pnlSuperior, javax.swing.BoxLayout.LINE_AXIS));

        lblJugadores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJugadores.setText("Partidas");
        pnlSuperior.add(lblJugadores);
        pnlSuperior.add(filler1);

        btnRefrescar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });
        pnlSuperior.add(btnRefrescar);

        add(pnlSuperior, java.awt.BorderLayout.NORTH);

        pnlCentro.setLayout(new java.awt.GridBagLayout());

        lblJuego.setText("Juego");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlCentro.add(lblJuego, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlCentro.add(cbxJuego, gridBagConstraints);

        lblJugador.setText("Jugador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlCentro.add(lblJugador, gridBagConstraints);

        cbxJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxJugadorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlCentro.add(cbxJugador, gridBagConstraints);

        btnFiltrar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlCentro.add(btnFiltrar, gridBagConstraints);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlCentro.add(btnLimpiar, gridBagConstraints);

        btnRegistrar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlCentro.add(btnRegistrar, gridBagConstraints);

        tblPartidas.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
        jspPartidas.setViewportView(tblPartidas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.9;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlCentro.add(jspPartidas, gridBagConstraints);

        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        mostrarPartidas();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cbxJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxJugadorActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        servicio.cargarBBDD();
        mostrarPartidas();
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        JPanel pnl = (JPanel) this.getParent();
        CardLayout cl = (CardLayout) pnl.getLayout();
        cl.show(pnl, "REGISTRAR");
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<Juego> cbxJuego;
    private javax.swing.JComboBox<Jugador> cbxJugador;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jspPartidas;
    private javax.swing.JLabel lblJuego;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblJugadores;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JTable tblPartidas;
    // End of variables declaration//GEN-END:variables

    private void inicializarTabla() {
        tblPartidas.setModel(new DefaultTableModel(new String[]{
            "Fecha",
            "Juego",
            "Duración",
            "Ganador",
            "Perdedor",
            "Puntuación"
        }, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return switch (columnIndex) {
                    case 0 ->
                        LocalDateTime.class;
                    case 1 ->
                        Juego.class;
                    case 3, 4 ->
                        Jugador.class;
                    case 5 ->
                        Integer.class;
                    default ->
                        String.class;
                };
            }
        });

        tblPartidas.setDefaultRenderer(LocalDateTime.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel lbl = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                LocalDateTime ldt = (LocalDateTime) value;
                lbl.setText(ldt.format(DateTimeFormatter.ofPattern("dd MMM y HH:mm")));
                return lbl;
            }
        });

        tblPartidas.setDefaultRenderer(Juego.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel lbl = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                Juego j = (Juego) value;
                lbl.setText(j.getTitulo());
                lbl.setToolTipText(j.getDescripcion());
                return lbl;
            }
        });

        tblPartidas.setDefaultRenderer(Jugador.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel lbl = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                Jugador j = (Jugador) value;
                lbl.setText(j.getNick());
                lbl.setIcon(j.getImagenAvatar());
                lbl.setToolTipText("%s, %s".formatted(j.getNombre(), j.getApellidos()));
                return lbl;
            }
        });

        tblPartidas.setDefaultRenderer(Integer.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel lbl = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                Integer i = (Integer) value;
                lbl.setHorizontalAlignment(JLabel.CENTER);
                return lbl;
            }
        });
        tblPartidas.setAutoCreateRowSorter(true);
    }

    private void cargarJuegosCBX() {
        cbxJuego.addItem(null);
        for (Juego j : servicio.getJuegos()) {
            cbxJuego.addItem(j);
        }
    }

    private void cargarJugadoresCBX() {
        cbxJugador.addItem(null);
        for (Jugador j : servicio.getJugadores()) {
            cbxJugador.addItem(j);
        }
    }

    private void inicializarCBX() {
        cbxJuego.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel lbl = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                Juego j = (Juego) value;
                if (j != null) {
                    lbl.setText(j.getTitulo());
                    lbl.setToolTipText(j.getDescripcion());
                } else {
                    lbl.setText("--- Seleccione un juego ---");
                }
                lbl.setPreferredSize(new Dimension(100, 45));
                return lbl;
            }
        });

        cbxJugador.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel lbl = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                Jugador j = (Jugador) value;
                if (j != null) {
                    lbl.setText(j.getNick());
                    lbl.setIcon(j.getImagenAvatar());
                    lbl.setToolTipText("%s, %s".formatted(j.getNombre(), j.getApellidos()));
                } else {
                    lbl.setText("--- Seleccione un jugador ---");
                }
                lbl.setPreferredSize(new Dimension(100, 45));
                return lbl;
            }
        });
        cargarJugadoresCBX();
        cargarJuegosCBX();
    }

    private void mostrarPartidas() {
        Juego juego = (Juego) cbxJuego.getSelectedItem();
        Jugador jugador = (Jugador) cbxJugador.getSelectedItem();
        /*
         List<Partida> partidas = new ArrayList<>();
        for (Partida p : servicio.getPartidas()) {
            if (juego == null && jugador == null) {
                // No hay ni juego ni partida
                partidas.add(p);
            } else if (juego != null && jugador == null && p.getJuego().equals(juego)) {
                //Sólo hay juego y la partida es de ese juego.
                partidas.add(p);
            } else if (juego == null && jugador != null && p.getGana().equals(jugador) || p.getPierde().equals(jugador)) {
                // Sólo hay jugador y es uno de los que gana o pierde
                partidas.add(p);
            } else if (p.getJuego().equals(juego) && p.getGana().equals(jugador) || p.getPierde().equals(jugador)){
                // Todo coincide
                partidas.add(p);
            }*/
        List<Partida> partidas = servicio.getPartidas();
        if (juego != null) {
            partidas = partidas.stream()
                    .filter(p -> p.getJuego().equals(juego))
                    .toList();
        }
        if (jugador != null) {
            partidas = partidas.stream()
                    .filter(p -> p.getGana().equals(jugador) || p.getPierde().equals(jugador))
                    .toList();
        }
        DefaultTableModel dtm = (DefaultTableModel) tblPartidas.getModel();
        dtm.setRowCount(0);
        for (Partida partida : partidas) {
            Vector vctFila = new Vector();
            vctFila.add(partida.getFecha());
             vctFila.add(partida.getJuego());
             vctFila.add(partida.getDuracion());
             vctFila.add(partida.getGana());
             vctFila.add(partida.getPierde());
             vctFila.add(partida.getPuntos());
             dtm.addRow(vctFila);
        }
    }

}
