/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.zabalburu.daw1.aplicaciontorneo.vista.paneles;

import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;
import com.github.lgooddatepicker.components.DateTimePicker;
import com.github.lgooddatepicker.components.TimePickerSettings;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.time.LocalDateTime;
import java.util.Locale;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import org.zabalburu.daw1.aplicaciontorneo.modelo.Juego;
import org.zabalburu.daw1.aplicaciontorneo.modelo.Jugador;
import org.zabalburu.daw1.aplicaciontorneo.modelo.Partida;
import org.zabalburu.daw1.aplicaciontorneo.servicio.TorneoServicio;

/**
 *
 * @author DAW1
 */
public class PnlRegistro extends javax.swing.JPanel {

    private DateTimePicker datePicker;
    private TorneoServicio servicio = TorneoServicio.getServicio();

    /**
     * Creates new form PnlRegistro
     */
    public PnlRegistro() {
        initComponents();
        Locale lopesp = new Locale("es", "ES");
        DatePickerSettings dateSettings = new DatePickerSettings(lopesp);
        TimePickerSettings timeSettings = new TimePickerSettings(lopesp);
        timeSettings.setFormatForDisplayTime("HH:mm");
        timeSettings.setFormatForMenuTimes("HH:mm");
        datePicker = new DateTimePicker(dateSettings, timeSettings);
        datePicker.setDateTimeStrict(LocalDateTime.now());
        GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlDatos.add(datePicker, gridBagConstraints);
        inicializarCombos();
        cargarJuegos();
        cargarJugadores();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jComboBox3 = new javax.swing.JComboBox<>();
        pnlDatos = new javax.swing.JPanel();
        lblJuego = new javax.swing.JLabel();
        cbxJuego = new javax.swing.JComboBox<>();
        lblGanador = new javax.swing.JLabel();
        cbxGanador = new javax.swing.JComboBox<>();
        lblPerdedor = new javax.swing.JLabel();
        cbxPerdedor = new javax.swing.JComboBox<>();
        lblPuntos = new javax.swing.JLabel();
        spiPuntos = new javax.swing.JSpinner();
        lblDuracion = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        bntBotones = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        pnlSuperior = new javax.swing.JPanel();
        lblRegistrar = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnLimpiar = new javax.swing.JButton();

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout());

        pnlDatos.setLayout(new java.awt.GridBagLayout());

        lblJuego.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJuego.setText("Juego");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlDatos.add(lblJuego, gridBagConstraints);

        cbxJuego.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxJuegoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlDatos.add(cbxJuego, gridBagConstraints);

        lblGanador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGanador.setText("Ganador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlDatos.add(lblGanador, gridBagConstraints);

        cbxGanador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlDatos.add(cbxGanador, gridBagConstraints);

        lblPerdedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPerdedor.setText("Perdedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlDatos.add(lblPerdedor, gridBagConstraints);

        cbxPerdedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlDatos.add(cbxPerdedor, gridBagConstraints);

        lblPuntos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPuntos.setText("Puntos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlDatos.add(lblPuntos, gridBagConstraints);

        spiPuntos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spiPuntos.setModel(new javax.swing.SpinnerNumberModel(5, 5, 500, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlDatos.add(spiPuntos, gridBagConstraints);

        lblDuracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDuracion.setText("Duración");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlDatos.add(lblDuracion, gridBagConstraints);

        txtDuracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlDatos.add(txtDuracion, gridBagConstraints);

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFecha.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlDatos.add(lblFecha, gridBagConstraints);

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        bntBotones.add(btnCancelar);

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        bntBotones.add(btnGuardar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlDatos.add(bntBotones, gridBagConstraints);

        add(pnlDatos, java.awt.BorderLayout.CENTER);

        pnlSuperior.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 5, 0));
        pnlSuperior.setLayout(new javax.swing.BoxLayout(pnlSuperior, javax.swing.BoxLayout.LINE_AXIS));

        lblRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRegistrar.setText("Registrar Partida");
        pnlSuperior.add(lblRegistrar);
        pnlSuperior.add(filler1);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        pnlSuperior.add(btnLimpiar);

        add(pnlSuperior, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxJuegoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        inicializarDatos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Jugador ganador = (Jugador) cbxGanador.getSelectedItem();
        Jugador perdedor = (Jugador) cbxPerdedor.getSelectedItem();
        if (ganador.equals(perdedor)){
            JOptionPane.showMessageDialog(null, "Debe seleccionar jugadores diferentes!", "Selección", JOptionPane.ERROR_MESSAGE);
        } else {
            Juego j = (Juego) cbxJuego.getSelectedItem();
            Partida p = new Partida();
            p.setJuego(j);
            p.setGana(ganador);
            p.setPierde(perdedor);
            p.setFecha(datePicker.getDateTimeStrict());
            p.setDuracion(txtDuracion.getText());
            p.setPuntos((Integer) spiPuntos.getValue());
            servicio.addPartida(p);
            JOptionPane.showMessageDialog(null, "partida registrada con éxito", "Partida Guardada", JOptionPane.INFORMATION_MESSAGE);
            inicializarDatos();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bntBotones;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<Jugador> cbxGanador;
    private javax.swing.JComboBox<Juego> cbxJuego;
    private javax.swing.JComboBox<Jugador> cbxPerdedor;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblGanador;
    private javax.swing.JLabel lblJuego;
    private javax.swing.JLabel lblPerdedor;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JSpinner spiPuntos;
    private javax.swing.JTextField txtDuracion;
    // End of variables declaration//GEN-END:variables

    private void cargarJuegos() {
        for (Juego juego : servicio.getJuegos()) {
            cbxJuego.addItem(juego);
        }
    }

    private void cargarJugadores() {
        for (Jugador jugador : servicio.getJugadores()) {
            cbxGanador.addItem(jugador);
            cbxPerdedor.addItem(jugador);
        }
    }

    private void inicializarCombos() {
        cbxJuego.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel lbl = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                Juego j = (Juego) value;
                lbl.setText(j.getTitulo());
                return lbl;
            }

        });

        ListCellRenderer r = new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel lbl = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                Jugador j = (Jugador) value;
                lbl.setText(j.getNick());
                lbl.setToolTipText("%s, %s [id:%d]".formatted(j.getApellidos(), j.getNombre(), j.getId()));
                lbl.setIcon(j.getImagenAvatar());
                return lbl;
            }
        };

        cbxGanador.setRenderer(r);
        cbxPerdedor.setRenderer(r);
    }

    public void inicializarDatos() {
        cbxJuego.setSelectedIndex(0);
        cbxGanador.setSelectedIndex(0);
        cbxPerdedor.setSelectedIndex(0);
        datePicker.setDateTimeStrict(LocalDateTime.now());
        spiPuntos.setValue(5);
        txtDuracion.setText("");
    }
}
