/*
===== EXAMEN 3ra EVALUACIÓN ===== 
*/

CREATE TABLE TECNICOS (
IDTECNICO NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(100) NOT NULL,
ESPECIALIDAD VARCHAR2(100) NOT NULL
);
CREATE TABLE MAQUINAS (
IDMAQUINA NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(100) NOT NULL,
UBICACION VARCHAR2(100),
IDTECNICO NUMBER REFERENCES TECNICOS(IDTECNICO)
);
CREATE TABLE REVISIONES (
IDREVISION NUMBER PRIMARY KEY,
IDMAQUINA NUMBER REFERENCES MAQUINAS(IDMAQUINA),
FECHA DATE,
DESCRIPCION VARCHAR2(200),
COSTE NUMBER(10,2)
);