/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.daw1.cinemamanagement.vista;

import java.awt.CardLayout;
import org.zabalburu.daw1.cinemamanagement.servicio.CinemaServicio;
import org.zabalburu.daw1.cinemamanagement.vista.paneles.PnlDashboard;
import org.zabalburu.daw1.cinemamanagement.vista.paneles.PnlPeliculas;
import org.zabalburu.daw1.cinemamanagement.vista.paneles.PnlSesiones;

/**
 *
 * @author Iker Navarro Pérez
 */
public class FrmCinema extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCinema.class.getName());
    
    private static CinemaServicio servicio = CinemaServicio.getServicio();

    /**
     * Creates new form FrmCinema
     */
    public FrmCinema() {
        initComponents();
        pnlContenido.add(new PnlDashboard(), "DASHBOARD");
        pnlContenido.add(new PnlPeliculas(), "PELICULAS");
        pnlContenido.add(new PnlSesiones(), "SESIONES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grpBotones = new javax.swing.ButtonGroup();
        pnlSuperior = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(32767, 0));
        jLabel1 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(32767, 0));
        txtBuscador = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(250, 0), new java.awt.Dimension(32767, 0));
        lblUsuario = new javax.swing.JLabel();
        lblAvatarUsuario = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnPeliculas = new javax.swing.JButton();
        btnSesiones = new javax.swing.JButton();
        pnlEspacioVacio = new javax.swing.JPanel();
        pnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSuperior.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        pnlSuperior.setLayout(new javax.swing.BoxLayout(pnlSuperior, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/daw1/cinemamanagement/vista/logo_cine.png"))); // NOI18N
        pnlSuperior.add(jLabel2);

        lblTitulo.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        lblTitulo.setText("Cine Master");
        pnlSuperior.add(lblTitulo);
        pnlSuperior.add(filler1);

        jLabel1.setText("🔎");
        pnlSuperior.add(jLabel1);
        pnlSuperior.add(filler3);

        txtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorActionPerformed(evt);
            }
        });
        pnlSuperior.add(txtBuscador);
        pnlSuperior.add(filler2);

        lblUsuario.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblUsuario.setText("jLabel1");
        pnlSuperior.add(lblUsuario);

        lblAvatarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/daw1/cinemamanagement/vista/user-244 (1).png"))); // NOI18N
        pnlSuperior.add(lblAvatarUsuario);

        getContentPane().add(pnlSuperior, java.awt.BorderLayout.PAGE_START);

        pnlBotones.setLayout(new java.awt.GridBagLayout());

        btnDashboard.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 11, 10, 11);
        pnlBotones.add(btnDashboard, gridBagConstraints);

        btnPeliculas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPeliculas.setText("Películas");
        btnPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeliculasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 11, 10, 11);
        pnlBotones.add(btnPeliculas, gridBagConstraints);

        btnSesiones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSesiones.setText("Sesiones");
        btnSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesionesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 11, 10, 11);
        pnlBotones.add(btnSesiones, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 1.0;
        pnlBotones.add(pnlEspacioVacio, gridBagConstraints);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.WEST);

        pnlContenido.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        cambiarPanel("DASHBOARD");
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliculasActionPerformed
        cambiarPanel("PELICULAS");
    }//GEN-LAST:event_btnPeliculasActionPerformed

    private void btnSesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesionesActionPerformed
        cambiarPanel("SESIONES");
    }//GEN-LAST:event_btnSesionesActionPerformed
    private void cambiarPanel(String nombre) {
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, nombre);
        pnlContenido.revalidate(); // Re-calcula el layout
        pnlContenido.repaint();    // Re-dibuja el panel
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCinema().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnPeliculas;
    private javax.swing.JButton btnSesiones;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.ButtonGroup grpBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAvatarUsuario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlEspacioVacio;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JTextField txtBuscador;
    // End of variables declaration//GEN-END:variables
}
