/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.daw1.alquileres.views;

import java.text.NumberFormat;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.List;
import java.util.Vector;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.zabalburu.daw1.alquileres.modelo.Alquiler;
import org.zabalburu.daw1.alquileres.modelo.Coche;
import org.zabalburu.daw1.alquileres.modelo.Estado;
import org.zabalburu.daw1.alquileres.service.AlquilerService;

/**
 *
 * @author ichueca
 */
public class FrmAlquileres extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAlquileres.class.getName());

    private static AlquilerService service = AlquilerService.getService();
    Estado actual = Estado.CONSULTA;
    
    int pos = 0; // El coche actual
    
    private Vector<String> vctTitulos = new Vector<>();
    
    private List<Coche> coches;
    
    private NumberFormat nfMoneda = NumberFormat.getCurrencyInstance();
    
    
    /**
     * Creates new form FrmAlquileres
     */
    public FrmAlquileres() {
        coches = service.getCoches();
        initComponents();
        vctTitulos.add("ID");
        vctTitulos.add("Cliente");
        vctTitulos.add("Fecha Alquiler");
        vctTitulos.add("Fecha Devolución");
        vctTitulos.add("Días");
        vctTitulos.add("Coste / Día");
        vctTitulos.add("Coste Total");
        vctTitulos.add("Reclamable");
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlTitulo = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        lblCosteDia = new javax.swing.JLabel();
        ftxCosteDia = new javax.swing.JFormattedTextField();
        lblAlquileres = new javax.swing.JLabel();
        jspAlquileres = new javax.swing.JScrollPane();
        tblAlquileres = new javax.swing.JTable();
        ftxTotal = new javax.swing.JFormattedTextField();
        btnNuevoAlquiler = new javax.swing.JButton();
        btnEliminarAlquiler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Alquileres");

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbltitulo.setText("Gestión de Alquileres");
        pnlTitulo.add(lbltitulo);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        btnPrimero.setText("|<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });
        pnlBotones.add(btnPrimero);

        btnAnterior.setText("<");
        btnAnterior.setPreferredSize(new java.awt.Dimension(72, 23));
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        pnlBotones.add(btnAnterior);

        lblStatus.setText("00 / 00");
        pnlBotones.add(lblStatus);

        btnSiguiente.setText(">");
        btnSiguiente.setPreferredSize(new java.awt.Dimension(72, 23));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        pnlBotones.add(btnSiguiente);

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        pnlBotones.add(btnUltimo);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        pnlBotones.add(btnNuevo);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnModificar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelar);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnGuardar);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnEliminar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblId.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(lblId, gridBagConstraints);

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(txtId, gridBagConstraints);

        lblMarca.setText("Marca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(lblMarca, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(txtMarca, gridBagConstraints);

        lblModelo.setText("Modelo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(lblModelo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(txtModelo, gridBagConstraints);

        lblMatricula.setText("Matrícula");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(lblMatricula, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(txtMatricula, gridBagConstraints);

        lblColor.setText("Color");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(lblColor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(txtColor, gridBagConstraints);

        lblCosteDia.setText("Coste / Día");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(lblCosteDia, gridBagConstraints);

        ftxCosteDia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(ftxCosteDia, gridBagConstraints);

        lblAlquileres.setText("Alquileres");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(lblAlquileres, gridBagConstraints);

        tblAlquileres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspAlquileres.setViewportView(tblAlquileres);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(jspAlquileres, gridBagConstraints);

        ftxTotal.setEditable(false);
        ftxTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0"))));
        ftxTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftxTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(ftxTotal, gridBagConstraints);

        btnNuevoAlquiler.setText("Nuevo Alquiler");
        btnNuevoAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAlquilerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 5, 5, 5);
        jPanel1.add(btnNuevoAlquiler, gridBagConstraints);

        btnEliminarAlquiler.setText("Eliminar Alquiler");
        btnEliminarAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlquilerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 5, 5, 5);
        jPanel1.add(btnEliminarAlquiler, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(787, 461));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        pos=0;
        mostrar();
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        pos--;
        mostrar();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        pos++;
        mostrar();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        pos = coches.size() - 1;
        mostrar();
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        actual = Estado.ALTA;
        mostrar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        actual = Estado.MODIFICACION;
        mostrar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        actual = Estado.CONSULTA;
        mostrar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Coche coche = new Coche();
        if (actual == Estado.MODIFICACION){
            //coche.setId(Integer.getInteger(txtId.getText()));
            coche.setId(coches.get(pos).getId());
        }
        if (txtMarca.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "La MARCA es OBLIGATORIA!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            txtMarca.requestFocus();
        } else if (txtModelo.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "El MODELO es OBLIGATORIO!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            txtModelo.requestFocus();
        } else if (txtMatricula.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "La MATRÍCULA es OBLIGATORIA!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            txtMatricula.requestFocus();
        } else{
            coche.setColor(txtColor.getText());
            Number n = (Number) ftxCosteDia.getValue();
            coche.setCosteDia(n.doubleValue());
            coche.setMarca(txtMarca.getText());
            coche.setMatricula(txtMatricula.getText());
            coche.setModelo(txtModelo.getText());
            if (actual == Estado.ALTA){
                coche = service.nuevoCoche(coche);
            } else {
                service.modificarCoche(coche);
            }
            coches = service.getCoches();
            pos = coches.indexOf(coche);
            actual = Estado.CONSULTA;
            mostrar();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (JOptionPane.showConfirmDialog(this,
            "Eliminar el Coche %s [ %s ]".formatted(coches.get(pos).getMarca(),
                coches.get(pos).getMatricula()),
            "Eliminar",
            JOptionPane.YES_NO_OPTION
            ) == JOptionPane.YES_OPTION){
            service.eliminarCoche(coches.get(pos).getId());
            coches = service.getCoches();
            if (pos == coches.size()){
                pos--;
            }
            mostrar();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminarAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlquilerActionPerformed
        int fila = tblAlquileres.getSelectedRow();
        if (fila == -1){
            JOptionPane.showMessageDialog(this, 
                "Debe seleccionar el alquiler a eliminar",
                "Seleccione",
                JOptionPane.WARNING_MESSAGE);
        } else {
            Alquiler eliminar = coches.get(pos)
              .getAlquileres()
              .get(fila);
            service.eliminarAlquiler(eliminar.getId());
            coches = service.getCoches();
            mostrar();
        }
    }//GEN-LAST:event_btnEliminarAlquilerActionPerformed

    private void btnNuevoAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAlquilerActionPerformed
        new FrmNuevoAlquiler(this,true, coches.get(pos)).setVisible(true);
        coches = service.getCoches();
        mostrar();
    }//GEN-LAST:event_btnNuevoAlquilerActionPerformed

    private void mostrar() {
        if (coches.isEmpty()){
            actual = Estado.ALTA;
            pos = 0;
        }
        if (actual == Estado.ALTA){
            txtId.setText("");
            ftxCosteDia.setValue(50.0);
            txtMarca.setText("");
            txtModelo.setText("");
            txtMatricula.setText("");
            txtColor.setText("");
            ftxTotal.setValue(0.0);
            lblStatus.setText("Nuevo");
        } else {
            Coche coche = coches.get(pos);
            txtId.setText(String.valueOf(coche.getId()));
            ftxCosteDia.setValue(coche.getCosteDia());
            txtMarca.setText(coche.getMarca());
            txtModelo.setText(coche.getModelo());
            txtMatricula.setText(coche.getMatricula());
            txtColor.setText(coche.getColor());
            lblStatus.setText("%02d/%02d".formatted(pos + 1, coches.size() ));
        }
        btnAnterior.setEnabled(pos > 0 && actual == Estado.CONSULTA);
        btnPrimero.setEnabled(pos > 0 && actual == Estado.CONSULTA);
        btnSiguiente.setEnabled(pos < coches.size() - 1 && actual == Estado.CONSULTA);
        btnUltimo.setEnabled(pos < coches.size() - 1 && actual == Estado.CONSULTA);
        btnCancelar.setEnabled(actual != Estado.CONSULTA && coches.size() > 0 );
        btnGuardar.setEnabled(actual != Estado.CONSULTA);
        btnModificar.setEnabled(actual == Estado.CONSULTA);
        btnNuevo.setEnabled(actual == Estado.CONSULTA);
        btnEliminar.setEnabled(actual == Estado.CONSULTA);
        txtColor.setEditable(actual != Estado.CONSULTA);
        txtMarca.setEditable(actual != Estado.CONSULTA);
        txtMatricula.setEditable(actual != Estado.CONSULTA);
        txtModelo.setEditable(actual != Estado.CONSULTA);
        ftxCosteDia.setEditable(actual != Estado.CONSULTA);
        if (actual == Estado.ALTA){
            DefaultTableModel dtm = (DefaultTableModel) tblAlquileres.getModel();
            dtm.setDataVector(null, vctTitulos);
        } else {
            cargarAlquileres();
        }
    }

    private void cargarAlquileres() {
        Vector<Vector<String>> vctDatos = new Vector<>();
        Double total = 0.0;
        for (Alquiler a : coches.get(pos).getAlquileres()) {
            Vector<String> vctFila = new Vector<>();
            vctFila.add(a.getId().toString());
            vctFila.add(a.getCliente().nombre());
            vctFila.add(a.getFechaAlquiler().format(DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM)));
            if (a.getFechaDevolucion() != null){
                vctFila.add(a.getFechaDevolucion().format(DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM)));
            } else {
                vctFila.add("");
            }
            vctFila.add(a.getDias().toString());
            vctFila.add(nfMoneda.format(a.getCosteDia()));
            vctFila.add(nfMoneda.format(a.getCosteTotal()));
            vctFila.add((a.isReclamable()?"Sí":"No"));
            vctDatos.add(vctFila);
            total += a.getCosteTotal();
        }
        ftxTotal.setValue(total);
        /*ftxTotal.setValue(coches.get(pos).getAlquileres()
            .stream()
            .collect(Collectors.summingDouble(a -> a.getCosteTotal())));*/
        /*DefaultTableModel dtm = new DefaultTableModel(vctDatos, vctTitulos);
        tblAlquileres.setModel(dtm);*/
        DefaultTableModel dtm = (DefaultTableModel) tblAlquileres.getModel();
        dtm.setDataVector(vctDatos, vctTitulos);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAlquileres().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarAlquiler;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevoAlquiler;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JFormattedTextField ftxCosteDia;
    private javax.swing.JFormattedTextField ftxTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jspAlquileres;
    private javax.swing.JLabel lblAlquileres;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblCosteDia;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTable tblAlquileres;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables


}
