/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.zabalburu.daw1.alquileres.views;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import org.zabalburu.daw1.alquileres.modelo.Alquiler;
import org.zabalburu.daw1.alquileres.modelo.Cliente;
import org.zabalburu.daw1.alquileres.modelo.Coche;
import org.zabalburu.daw1.alquileres.service.AlquilerService;
import org.zabalburu.daw1.alquileres.util.DateConversion;

/**
 *
 * @author ichueca
 */
public class FrmNuevoAlquiler extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmNuevoAlquiler.class.getName());

    private static final AlquilerService service = AlquilerService.getService();
    
    private Coche coche;
    
    /**
     * Creates new form FrmNuevoAlquiler
     */
    public FrmNuevoAlquiler(java.awt.Frame parent, boolean modal, Coche coche) {
        super(parent, modal);
        this.coche = coche;
        initComponents();
        cargarClientes();
        lblCoche.setText(
           "%s %s [ %s ] - %s".formatted(coche.getMarca()
                ,coche.getModelo()
                ,coche.getColor()
                ,coche.getMatricula()));
        
        //ftxFecha.setValue(Date.from(Instant.now()));
        ftxFecha.setValue(DateConversion.fromLocalDate(LocalDate.now()));
        ftxDias.setValue(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCoche = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ftxFecha = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        ftxDias = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        cbxCliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Alquiler");
        getContentPane().setLayout(null);

        lblCoche.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCoche.setText("jLabel1");
        getContentPane().add(lblCoche);
        lblCoche.setBounds(60, 50, 370, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Fecha Alquiler");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 150, 100, 20);

        ftxFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        ftxFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(ftxFecha);
        ftxFecha.setBounds(190, 150, 130, 26);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Días");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 190, 100, 20);

        ftxDias.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        ftxDias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(ftxDias);
        ftxDias.setBounds(190, 190, 130, 26);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cliente");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 110, 100, 20);

        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(200, 260, 130, 30);

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevo.setText("Añadir Alquiler");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo);
        btnNuevo.setBounds(50, 260, 130, 30);

        cbxCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(cbxCliente);
        cbxCliente.setBounds(190, 100, 190, 26);

        setSize(new java.awt.Dimension(451, 349));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        Alquiler a = new Alquiler();
        Cliente c = (Cliente) cbxCliente.getSelectedItem();
        a.setCliente(c);
        a.setCoche(coche);
        a.setCosteDia(coche.getCosteDia());
        Number n = (Number) ftxDias.getValue();
        a.setDias(n.intValue());
        Date d = (Date) ftxFecha.getValue();
        a.setFechaAlquiler(DateConversion.fromDate(d));
        a.setFechaDevolucion(null);
        service.nuevoAlquiler(a);
        JOptionPane.showMessageDialog(this, 
            "Alquiler registrado con Éxito!");
        this.dispose();
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<Cliente> cbxCliente;
    private javax.swing.JFormattedTextField ftxDias;
    private javax.swing.JFormattedTextField ftxFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCoche;
    // End of variables declaration//GEN-END:variables

    private void cargarClientes() {
        for(Cliente c : service.getClientes()
                .stream()
                .sorted((c1,c2) -> c1.nombre().compareToIgnoreCase(c2.nombre()))
                .toList()){
            cbxCliente.addItem(c);
        }
    }
    
    public static void main(String[] args) {
        new FrmNuevoAlquiler(null, true, service.getCoches().get(0)).setVisible(true);
    }
}
