/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.zabalburu.gestion_streamers.view.panels;

import org.zabalburu.gestion_streamers.service.GestionService;

/**
 *
 * @author Iker Navarro Pérez
 */
public class PnlDashboard extends javax.swing.JPanel {

    private GestionService service = GestionService.getService();

    /**
     * Creates new form PnlDashboard
     */
    public PnlDashboard() {
        initComponents();
        actualizarContadores();
    }

    private void actualizarContadores() {
        lblTotalStreamers.setText(String.valueOf(service.getStreamers().size()));
        lblTotalSesiones.setText(String.valueOf(service.getSesiones().size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlSuperior = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        lblStreamers = new javax.swing.JLabel();
        lblTotalStreamers = new javax.swing.JLabel();
        lblSesiones = new javax.swing.JLabel();
        lblTotalSesiones = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(620, 600));
        setLayout(new java.awt.BorderLayout());

        pnlSuperior.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblDashboard.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblDashboard.setText("Dashboard");
        pnlSuperior.add(lblDashboard);

        add(pnlSuperior, java.awt.BorderLayout.PAGE_START);

        pnlCentro.setLayout(new java.awt.GridBagLayout());

        lblStreamers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStreamers.setText("Total Streamers");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        pnlCentro.add(lblStreamers, gridBagConstraints);

        lblTotalStreamers.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTotalStreamers.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        pnlCentro.add(lblTotalStreamers, gridBagConstraints);

        lblSesiones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSesiones.setText("Total Sesiones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        pnlCentro.add(lblSesiones, gridBagConstraints);

        lblTotalSesiones.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTotalSesiones.setText("jLabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        pnlCentro.add(lblTotalSesiones, gridBagConstraints);

        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblSesiones;
    private javax.swing.JLabel lblStreamers;
    private javax.swing.JLabel lblTotalSesiones;
    private javax.swing.JLabel lblTotalStreamers;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlSuperior;
    // End of variables declaration//GEN-END:variables

}
