/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.gestion_streamers.view;

import java.awt.CardLayout;
import org.zabalburu.gestion_streamers.view.panels.PnlDashboard;
import org.zabalburu.gestion_streamers.view.panels.PnlSesiones;
import org.zabalburu.gestion_streamers.view.panels.PnlStreamers;

/**
 *
 * @author Iker Navarro Pérez
 */
public class FrmMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenu.class.getName());

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        pnlContenido.add(new PnlDashboard(), "DASHBOARD");
        pnlContenido.add(new PnlStreamers(), "STREAMERS");
        pnlContenido.add(new PnlSesiones(), "SESIONES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlMenuIzquierdo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        fllRelleno1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        tbtDashboard = new javax.swing.JToggleButton();
        tbtStreamers = new javax.swing.JToggleButton();
        tbtSesiones = new javax.swing.JToggleButton();
        fllRelleno2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        pnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión Streamers - Iker Navarro Pérez");
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        pnlMenuIzquierdo.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        pnlMenuIzquierdo.setPreferredSize(new java.awt.Dimension(180, 600));
        pnlMenuIzquierdo.setLayout(new java.awt.GridBagLayout());

        lblLogo.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/gestion_streamers/view/logo.png"))); // NOI18N
        lblLogo.setText("Gestión Streamers");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlMenuIzquierdo.add(lblLogo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        pnlMenuIzquierdo.add(fllRelleno1, gridBagConstraints);

        buttonGroup1.add(tbtDashboard);
        tbtDashboard.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        tbtDashboard.setText("💻 Dashboard");
        tbtDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtDashboardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        pnlMenuIzquierdo.add(tbtDashboard, gridBagConstraints);

        buttonGroup1.add(tbtStreamers);
        tbtStreamers.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        tbtStreamers.setText("👨‍💻 Streamers");
        tbtStreamers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtStreamersActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        pnlMenuIzquierdo.add(tbtStreamers, gridBagConstraints);

        buttonGroup1.add(tbtSesiones);
        tbtSesiones.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        tbtSesiones.setText("🎥 Sesiones");
        tbtSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtSesionesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        pnlMenuIzquierdo.add(tbtSesiones, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.9;
        pnlMenuIzquierdo.add(fllRelleno2, gridBagConstraints);

        getContentPane().add(pnlMenuIzquierdo, java.awt.BorderLayout.LINE_START);

        pnlContenido.setPreferredSize(new java.awt.Dimension(620, 600));
        pnlContenido.setLayout(new java.awt.CardLayout(20, 20));
        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbtDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtDashboardActionPerformed
        cambiarPnl("DASHBOARD");
    }//GEN-LAST:event_tbtDashboardActionPerformed

    private void tbtStreamersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtStreamersActionPerformed
        cambiarPnl("STREAMERS");
    }//GEN-LAST:event_tbtStreamersActionPerformed

    private void tbtSesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtSesionesActionPerformed
        cambiarPnl("SESIONES");
    }//GEN-LAST:event_tbtSesionesActionPerformed

    private void cambiarPnl(String nombrePnl) {
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, nombrePnl);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler fllRelleno1;
    private javax.swing.Box.Filler fllRelleno2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlMenuIzquierdo;
    private javax.swing.JToggleButton tbtDashboard;
    private javax.swing.JToggleButton tbtSesiones;
    private javax.swing.JToggleButton tbtStreamers;
    // End of variables declaration//GEN-END:variables

}
