/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.daw1.prueba_gestionbanco_1.vista;

import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.zabalburu.daw1.prueba_gestionbanco_1.modelo.Cliente;
import org.zabalburu.daw1.prueba_gestionbanco_1.modelo.CuentaBancaria;
import org.zabalburu.daw1.prueba_gestionbanco_1.servicio.BancoServicio;
import org.zabalburu.daw1.prueba_gestionbanco_1.util.DateConversion;
import org.zabalburu.daw1.prueba_gestionbanco_1.util.Estado;

/**
 *
 * @author Focus Mode
 */
public class ClienteFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteFrame.class.getName());

    private static BancoServicio servicio = BancoServicio.getInstance();
    Estado estado = Estado.CONSULTA;
    int pos = 0; //En que posición estamos.
    private List<Cliente> clientes = servicio.getClientes();
    private NumberFormat nfMoneda = NumberFormat.getCurrencyInstance();
    private Vector<String> vctTitulosTabla = new Vector<>();

    /**
     * Creates new form ClienteFrame
     */
    public ClienteFrame() {
        initComponents();
        vctTitulosTabla.add("ID");
        vctTitulosTabla.add("Nro Cuenta");
        vctTitulosTabla.add("Tipo");
        vctTitulosTabla.add("Fecha Apertura");
        vctTitulosTabla.add("Titular");
        vctTitulosTabla.add("Saldo");
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspCuentasBancarias = new javax.swing.JScrollPane();
        tblCuentasBancarias = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        lblContadorPos = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblNroTelefono = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblFechaAlta = new javax.swing.JLabel();
        ftxFechaNacimiento = new javax.swing.JFormattedTextField();
        ftxFechaAlta = new javax.swing.JFormattedTextField();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblTituloCliente = new javax.swing.JLabel();
        ftxSaldoTotal = new javax.swing.JFormattedTextField();
        lblSaldoTotal = new javax.swing.JLabel();
        ftxNroTelefono = new javax.swing.JFormattedTextField();
        btnNuevaCuenta = new javax.swing.JButton();
        btnEliminarCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCuentasBancarias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspCuentasBancarias.setViewportView(tblCuentasBancarias);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitulo.setText("Gestión Banco");

        btnPrimero.setText("|<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        lblContadorPos.setText("0 / 0");

        lblId.setText("ID");

        lblNombre.setText("Nombre");

        lblEmail.setText("Email");

        lblNroTelefono.setText("Nro Teléfono");

        lblFechaNacimiento.setText("Fecha Nacimiento");

        lblFechaAlta.setText("Fecha Alta Cliente");

        ftxFechaNacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        ftxFechaAlta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblTituloCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCliente.setText("Cliente");

        ftxSaldoTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));

        lblSaldoTotal.setText("Saldo Total");

        ftxNroTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btnNuevaCuenta.setText("Nueva Cuenta");
        btnNuevaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaCuentaActionPerformed(evt);
            }
        });

        btnEliminarCuenta.setText("Eliminar Cuenta");
        btnEliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jspCuentasBancarias, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(btnNuevaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSaldoTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxSaldoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxFechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblId)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(ftxFechaAlta)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTituloCliente)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(lblContadorPos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNroTelefono)
                                    .addComponent(lblFechaNacimiento)
                                    .addComponent(lblFechaAlta))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ftxNroTelefono))))
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(753, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTituloCliente)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNroTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxNroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFechaNacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFechaAlta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrimero)
                            .addComponent(btnAnterior)
                            .addComponent(btnSiguiente)
                            .addComponent(btnUltimo)
                            .addComponent(lblContadorPos))
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jspCuentasBancarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftxSaldoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSaldoTotal)
                            .addComponent(btnNuevaCuenta)
                            .addComponent(btnEliminarCuenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar)
                            .addComponent(btnGuardar)
                            .addComponent(btnEliminar)
                            .addComponent(btnCancelar))
                        .addGap(18, 18, 18))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(505, Short.MAX_VALUE)
                    .addComponent(btnNuevo)
                    .addGap(18, 18, 18)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Eliminar el Almacén: { %s [ ID: %d ]}".formatted(clientes.get(pos).getNombre(), clientes.get(pos).getId()), "Eliminar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                servicio.removeCliente(clientes.get(pos).getId());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No ha sido posible eliminar el Cliente!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            clientes = servicio.getClientes();
            if (pos == clientes.size()) {
                pos--;
            }
            mostrar();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        estado = Estado.ALTA;
        mostrar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        estado = Estado.MODIFICACION;
        mostrar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        estado = Estado.CONSULTA;
        mostrar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        pos = 0;
        mostrar();
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        pos--;
        mostrar();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        pos = clientes.size() - 1;
        mostrar();
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        pos++;
        mostrar();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Cliente c = new Cliente();
        if (estado == Estado.MODIFICACION) {
            c.setId(clientes.get(pos).getId());
            c.setCuentasBancarias(clientes.get(pos).getCuentasBancarias());
        }
        if (txtNombre.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "El Nombre es OBLIGATORIO!", "Error", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
        } else if (txtEmail.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "El Email es OBLIGATORIO!", "Error", JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocus();
        } else if (ftxNroTelefono.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "El Nro de Telefono es OBLIGATORIO!", "Error", JOptionPane.ERROR_MESSAGE);
            ftxNroTelefono.requestFocus();
        } else if (ftxFechaNacimiento.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "La Fecha de Nacimiento es OBLIGATORIA!", "Error", JOptionPane.ERROR_MESSAGE);
            ftxFechaNacimiento.requestFocus();
        } else if (ftxFechaAlta.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "La Fecha de Alta es OBLIGATORIA!", "Error", JOptionPane.ERROR_MESSAGE);
            ftxFechaAlta.requestFocus();
        } else {
            c.setNombre(txtNombre.getText());
            c.setEmail(txtEmail.getText());
            c.setNroTelefono(ftxNroTelefono.getText());
            Date d = (Date) ftxFechaNacimiento.getValue();
            try {
                c.setFechaNacimiento(DateConversion.fromDate(d));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Formato de la Fecha de nacimiento introducido NO válido, restablecido a su valor anterior!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            d = (Date) ftxFechaAlta.getValue();
            try {
                c.setFechaAlta(DateConversion.fromDate(d));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Formato de la Fecha de alta introducido NO válido, restablecido a su valor anterior!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if (estado == Estado.ALTA) {
                servicio.addCliente(c);
            } else {
                servicio.modifyCliente(c);
            }
            clientes = servicio.getClientes();
            pos = clientes.indexOf(c);
            estado = Estado.CONSULTA;
            mostrar();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCuentaActionPerformed
        new CuentaBancariaFrame(this,true,clientes.get(pos)).setVisible(true);
        clientes = servicio.getClientes();
        mostrar();
    }//GEN-LAST:event_btnNuevaCuentaActionPerformed

    private void btnEliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCuentaActionPerformed
        int filaSeleccionada = tblCuentasBancarias.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar la Cuenta que desee ELIMINAR",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            CuentaBancaria eliminar = clientes.get(pos).getCuentasBancarias().get(filaSeleccionada);
            servicio.removeCuentaBancaria(eliminar.getId());
            clientes = servicio.getClientes();
            mostrar();
        }
    }//GEN-LAST:event_btnEliminarCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarCuenta;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevaCuenta;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JFormattedTextField ftxFechaAlta;
    private javax.swing.JFormattedTextField ftxFechaNacimiento;
    private javax.swing.JFormattedTextField ftxNroTelefono;
    private javax.swing.JFormattedTextField ftxSaldoTotal;
    private javax.swing.JScrollPane jspCuentasBancarias;
    private javax.swing.JLabel lblContadorPos;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFechaAlta;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNroTelefono;
    private javax.swing.JLabel lblSaldoTotal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloCliente;
    private javax.swing.JTable tblCuentasBancarias;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void mostrar() {
        if (clientes.isEmpty()) {
            estado = Estado.ALTA;
            pos = 0;
        }
        if (estado == Estado.ALTA) {
            lblContadorPos.setText("Nuevo");
            txtId.setText(" | Automático | ");
            ftxSaldoTotal.setText("0 €");
            txtNombre.setText("");
            txtEmail.setText("");
            ftxNroTelefono.setText("");
            ftxFechaNacimiento.setText("1950-01-01");
            ftxFechaAlta.setText(LocalDate.now().toString());
        } else {
            Cliente c = clientes.get(pos);
            txtId.setText(String.valueOf(c.getId()));
            ftxSaldoTotal.setText(nfMoneda.format(servicio.getSaldoTotalCliente(c.getId())));
            txtNombre.setText(c.getNombre());
            txtEmail.setText(c.getEmail());
            ftxNroTelefono.setText(c.getNroTelefono());
            ftxFechaNacimiento.setValue(DateConversion.fromLocalDate(c.getFechaNacimiento()));
            ftxFechaAlta.setValue(DateConversion.fromLocalDate(c.getFechaAlta()));
            lblContadorPos.setText("%02d / %02d".formatted(pos + 1, clientes.size()));
        }
        btnAnterior.setEnabled(pos > 0 && estado == Estado.CONSULTA);
        btnPrimero.setEnabled(pos > 0 && estado == Estado.CONSULTA);
        btnSiguiente.setEnabled(pos < clientes.size() - 1 && estado == Estado.CONSULTA);
        btnUltimo.setEnabled(pos < clientes.size() - 1 && estado == Estado.CONSULTA);
        btnCancelar.setEnabled(estado != Estado.CONSULTA && clientes.size() > 0);
        btnGuardar.setEnabled(estado != Estado.CONSULTA);
        btnModificar.setEnabled(estado == Estado.CONSULTA);
        btnNuevo.setEnabled(estado == Estado.CONSULTA);
        btnEliminar.setEnabled(estado == Estado.CONSULTA);
        btnNuevaCuenta.setEnabled(estado == Estado.CONSULTA);
        btnEliminarCuenta.setEnabled(estado == Estado.CONSULTA);
        txtId.setEnabled(false);
        ftxSaldoTotal.setEnabled(false);
        txtNombre.setEnabled(estado != Estado.CONSULTA);
        txtEmail.setEnabled(estado != Estado.CONSULTA);
        ftxNroTelefono.setEnabled(estado != Estado.CONSULTA);
        ftxFechaNacimiento.setEnabled(estado != Estado.CONSULTA);
        ftxFechaAlta.setEnabled(estado != Estado.CONSULTA);
        if (estado == Estado.ALTA) {
            DefaultTableModel dtmModelo = (DefaultTableModel) tblCuentasBancarias.getModel();
            dtmModelo.setDataVector(null, vctTitulosTabla);
        } else {
            cargarCuentasBancarias();
        }
    }

    private void cargarCuentasBancarias() {
        Vector<Vector<String>> vctDatos = new Vector<>();
        for (CuentaBancaria c : clientes.get(pos).getCuentasBancarias()) {
            Vector<String> vctFilaTabla = new Vector<>();
            vctFilaTabla.add(c.getId().toString());
            vctFilaTabla.add(c.getNroCuenta());
            vctFilaTabla.add(c.getTipo().toString());
            vctFilaTabla.add(c.getFechaApertura().toString());
            vctFilaTabla.add(c.getTitular().toString());
            vctFilaTabla.add(nfMoneda.format(c.getSaldo()));
            vctDatos.add(vctFilaTabla);
        }
        DefaultTableModel dtmModelo = (DefaultTableModel) tblCuentasBancarias.getModel();
        dtmModelo.setDataVector(vctDatos, vctTitulosTabla);
    }
}


