/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.zabalburu.daw1.cinemamanagement.vista.paneles;

import java.awt.Component;
import java.awt.Font;
import java.time.LocalDate;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.zabalburu.daw1.cinemamanagement.modelo.Pelicula;
import org.zabalburu.daw1.cinemamanagement.modelo.Sesion;
import org.zabalburu.daw1.cinemamanagement.servicio.CinemaServicio;

/**
 *
 * @author Focus Mode
 */
public class PnlDashboard extends javax.swing.JPanel {

    private CinemaServicio servicio = CinemaServicio.getServicio();
    private DefaultTableModel dtm;

    /**
     * Creates new form PnlDashboard
     */
    public PnlDashboard() {
        initComponents();
        inicializarTabla();
        actualizarPanel();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlNorte = new javax.swing.JPanel();
        fillerGlue3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(35, 0), new java.awt.Dimension(32767, 0));
        lblTitulo = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnCerrarSesión = new javax.swing.JButton();
        fillerGlue1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(32767, 0));
        fillerGlue2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(32767, 0));
        pnlCentro = new javax.swing.JPanel();
        pnlContenido = new javax.swing.JPanel();
        pnlEstadisticas = new javax.swing.JPanel();
        pnlTotalPeliculas = new javax.swing.JPanel();
        lblContadorTotalPeliculas = new javax.swing.JLabel();
        pnlTotalSesiones = new javax.swing.JPanel();
        lblContadorTotalSesiones = new javax.swing.JLabel();
        lblUltimasSesiones = new javax.swing.JLabel();
        jspSesiones = new javax.swing.JScrollPane();
        tblSesiones = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1200, 600));
        setLayout(new java.awt.BorderLayout());

        pnlNorte.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        pnlNorte.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weightx = 0.7;
        pnlNorte.add(fillerGlue3, gridBagConstraints);

        lblTitulo.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        lblTitulo.setText("Dashboard");
        lblTitulo.setPreferredSize(new java.awt.Dimension(200, 48));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlNorte.add(lblTitulo, gridBagConstraints);

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/daw1/cinemamanagement/vista/paneles/Sync.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlNorte.add(btnActualizar, gridBagConstraints);

        btnCerrarSesión.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesión.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/daw1/cinemamanagement/vista/paneles/Door.png"))); // NOI18N
        btnCerrarSesión.setText("Cerrar Sesión");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlNorte.add(btnCerrarSesión, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        pnlNorte.add(fillerGlue1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        pnlNorte.add(fillerGlue2, gridBagConstraints);

        add(pnlNorte, java.awt.BorderLayout.NORTH);

        pnlCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        pnlCentro.setLayout(new java.awt.BorderLayout());

        pnlContenido.setLayout(new java.awt.GridBagLayout());

        pnlEstadisticas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estadísticas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        pnlEstadisticas.setLayout(new java.awt.GridBagLayout());

        pnlTotalPeliculas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Películas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        pnlTotalPeliculas.setPreferredSize(new java.awt.Dimension(150, 64));
        pnlTotalPeliculas.setLayout(new java.awt.GridBagLayout());

        lblContadorTotalPeliculas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblContadorTotalPeliculas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContadorTotalPeliculas.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlTotalPeliculas.add(lblContadorTotalPeliculas, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEstadisticas.add(pnlTotalPeliculas, gridBagConstraints);

        pnlTotalSesiones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Sesiones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        pnlTotalSesiones.setPreferredSize(new java.awt.Dimension(150, 64));
        pnlTotalSesiones.setLayout(new java.awt.GridBagLayout());

        lblContadorTotalSesiones.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblContadorTotalSesiones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContadorTotalSesiones.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlTotalSesiones.add(lblContadorTotalSesiones, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEstadisticas.add(pnlTotalSesiones, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 5, 3);
        pnlContenido.add(pnlEstadisticas, gridBagConstraints);

        lblUltimasSesiones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUltimasSesiones.setText("Últimas Sesiones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(11, 3, 0, 3);
        pnlContenido.add(lblUltimasSesiones, gridBagConstraints);

        tblSesiones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jspSesiones.setViewportView(tblSesiones);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 5, 3);
        pnlContenido.add(jspSesiones, gridBagConstraints);

        pnlCentro.add(pnlContenido, java.awt.BorderLayout.CENTER);

        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        CinemaServicio.cargarBBDD();
        actualizarPanel();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrarSesión;
    private javax.swing.Box.Filler fillerGlue1;
    private javax.swing.Box.Filler fillerGlue2;
    private javax.swing.Box.Filler fillerGlue3;
    private javax.swing.JScrollPane jspSesiones;
    private javax.swing.JLabel lblContadorTotalPeliculas;
    private javax.swing.JLabel lblContadorTotalSesiones;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUltimasSesiones;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlEstadisticas;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlTotalPeliculas;
    private javax.swing.JPanel pnlTotalSesiones;
    private javax.swing.JTable tblSesiones;
    // End of variables declaration//GEN-END:variables

    private void inicializarTabla() {
        Vector<String> vctColumnas = new Vector();
        vctColumnas.add("ID Sesión");
        vctColumnas.add("Película");
        vctColumnas.add("Fecha");
        vctColumnas.add("Hora");
        vctColumnas.add("Sala");
        vctColumnas.add("Asientos Disponibles");

        tblSesiones.setDefaultRenderer(LocalDate.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel lbl = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                return lbl;
            }
        });

        tblSesiones.setDefaultRenderer(Integer.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel lbl = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                lbl.setFont(lbl.getFont().deriveFont(18f));
                lbl.setHorizontalAlignment(JLabel.CENTER);
                return lbl;
            }
        });

        tblSesiones.setDefaultRenderer(Pelicula.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel lbl = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                Pelicula p = (Pelicula) value;
                lbl.setText(p.getTitulo());
                lbl.setToolTipText("ID Película: %d".formatted(p.getIdPelicula()));
                return lbl;
            }
        });

        dtm = new DefaultTableModel(vctColumnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return switch (columnIndex) {
                    case 0, 4, 5 ->
                        Integer.class;
                    case 1 ->
                        Pelicula.class;
                    case 2 ->
                        LocalDate.class;
                    default ->
                        String.class;
                };
            }
        };

        tblSesiones.setModel(dtm);
        //tblSesiones.setAutoCreateRowSorter(true);
        tblSesiones.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void actualizarPanel() {
        lblContadorTotalPeliculas.setText(String.valueOf(servicio.getPeliculas().size()));
        lblContadorTotalSesiones.setText(String.valueOf(servicio.getSesiones().size()));
        dtm.setRowCount(0);
        for (Sesion s : servicio.getSesiones()
                .stream()
                .sorted((s1,s2) -> s2.getFecha().compareTo(s1.getFecha()))
                .toList()) {
            Vector vctFila = new Vector();
            vctFila.add(s.getIdSesion());
            vctFila.add(s.getPelicula());
            vctFila.add(s.getFecha());
            vctFila.add(s.getHora());
            vctFila.add(s.getSala());
            vctFila.add(s.getAsientosDisponibles());
            dtm.addRow(vctFila);
        }
    }

}
