/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.daw1.gestock.vista;

import java.awt.Component;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.util.List;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.zabalburu.daw1.gestock.excepciones.ProductoNoEncontradoException;
import org.zabalburu.daw1.gestock.excepciones.StockInsuficienteException;
import org.zabalburu.daw1.gestock.modelo.Almacen;
import org.zabalburu.daw1.gestock.modelo.Producto;
import org.zabalburu.daw1.gestock.servicio.GestockServicio;
import org.zabalburu.daw1.gestock.util.Categoria;
import org.zabalburu.daw1.gestock.util.Estado;

/**
 *
 * @author Iker Navarro Pérez
 */
public class ProductosAlmacenGestionVista extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductosAlmacenGestionVista.class.getName());
    private Estado estado = Estado.CONSULTA;
    int pos = 0;
    private boolean actualizandoTabla = false;
    private boolean busqueda = false;
    private static GestockServicio servicio = GestockServicio.getInstance();
    private Almacen almacen;
    private List<Producto> productos;
    private NumberFormat nfMoneda = NumberFormat.getCurrencyInstance();
    private DefaultTableModel dtm;

    /**
     * Creates new form ProductosAlmacenGestionVista
     */
    public ProductosAlmacenGestionVista(java.awt.Frame parent, boolean modal, Almacen almacen) {
        super(parent, modal);
        this.almacen = almacen;
        this.productos = cargarProductos();
        initComponents();
        this.setLocationRelativeTo(parent);
        inicializarTabla();
        cargarComboCategoria();
        tblProductos.getSelectionModel().addListSelectionListener(p -> {
            if (!p.getValueIsAdjusting() && !actualizandoTabla && tblProductos.getSelectedRow() != -1 && estado == Estado.CONSULTA) {
                pos = tblProductos.getSelectedRow();
                mostrar();
            }
        });
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspProductos = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        lblTituloGetock = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblCodigoBarras = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        ftxCodigoBarras = new javax.swing.JFormattedTextField();
        txtMarca = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        lblPrecio = new javax.swing.JLabel();
        ftxPrecio = new javax.swing.JFormattedTextField();
        ftxStock = new javax.swing.JFormattedTextField();
        lblStock = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        lblPrecio1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblProductos.getTableHeader().setResizingAllowed(false);
        tblProductos.getTableHeader().setReorderingAllowed(false);
        jspProductos.setViewportView(tblProductos);

        lblTituloGetock.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        lblTituloGetock.setText("GESTOCK");

        lblProducto.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblProducto.setText("Producto");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblId.setText("ID");

        lblCodigoBarras.setText("Código de Barras");

        lblDescripcion.setText("Descripción");

        ftxCodigoBarras.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftxCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxCodigoBarrasActionPerformed(evt);
            }
        });

        lblMarca.setText("Marca");

        lblCategoria.setText("Categoria");

        lblPrecio.setText("Precio €");

        ftxPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftxPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxPrecioActionPerformed(evt);
            }
        });

        ftxStock.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftxStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxStockActionPerformed(evt);
            }
        });

        lblStock.setText("Stock");

        txtBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarProductoActionPerformed(evt);
            }
        });

        lblPrecio1.setText("Buscar Producto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jspProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPrecio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProducto)
                        .addGap(18, 18, 18)
                        .addComponent(lblTituloGetock, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ftxPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPrecio, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ftxStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(lblStock, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDescripcion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblId)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblCodigoBarras)
                                    .addComponent(txtDescripcion)
                                    .addComponent(ftxCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(19, 19, 19)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCategoria)))))
                        .addContainerGap(41, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jspProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnAñadir)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar)
                            .addComponent(btnCancelar)
                            .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecio1))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloGetock, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCodigoBarras)
                        .addGap(3, 3, 3)
                        .addComponent(ftxCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescripcion)
                        .addGap(1, 1, 1)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarca)
                            .addComponent(lblCategoria))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblStock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Producto p = new Producto();
        if (estado == Estado.MODIFICACION) {
            p.setIdProducto(productos.get(pos).getIdProducto());
        }
        if (ftxCodigoBarras.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "El Código de Barras es OBLIGATORIO!", "Error", JOptionPane.ERROR_MESSAGE);
            ftxCodigoBarras.requestFocus();
        } else if (txtDescripcion.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "La Descripción es OBLIGATORIA!", "Error", JOptionPane.ERROR_MESSAGE);
            txtDescripcion.requestFocus();
        } else if (txtMarca.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "La Marca es OBLIGATORIA!", "Error", JOptionPane.ERROR_MESSAGE);
            txtMarca.requestFocus();
        } else if (ftxPrecio.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "El Precio es OBLIGATORIO!", "Error", JOptionPane.ERROR_MESSAGE);
            txtMarca.requestFocus();
        } else if (ftxStock.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "El Stock es OBLIGATORIO!", "Error", JOptionPane.ERROR_MESSAGE);
            ftxStock.requestFocus();
        } else {
            p.setCodigoBarras(ftxCodigoBarras.getText());
            p.setDescripcion(txtDescripcion.getText());
            p.setMarca(txtMarca.getText());
            p.setCategoria((Categoria) cbxCategoria.getSelectedItem());
            p.setPrecio(Double.valueOf(ftxPrecio.getText()));
            p.setStock(Integer.valueOf(ftxStock.getText()));
            p.setAlmacen(almacen);
            p.setFechaEntrada(LocalDate.now());
            if (estado == Estado.ALTA) {
                servicio.addProducto(p);
                JOptionPane.showMessageDialog(this, "El producto ha sido registrado de manera satisfactoria!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {
                    servicio.modifyProducto(p);
                } catch (StockInsuficienteException ex) {
                    System.getLogger(ProductosAlmacenGestionVista.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                } catch (ProductoNoEncontradoException ex) {
                    System.getLogger(ProductosAlmacenGestionVista.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                JOptionPane.showMessageDialog(this, "El producto ha sido modificado de manera satisfactoria!", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
            productos = cargarProductos();
            pos = productos.indexOf(p);
            estado = Estado.CONSULTA;
            mostrar();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        estado = Estado.ALTA;
        mostrar();
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        estado = Estado.MODIFICACION;
        mostrar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Desea eliminar el Producto: { %s [ ID: %d ]}".formatted(productos.get(pos).getDescripcion(), productos.get(pos).getIdProducto()), "Eliminar Producto", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                servicio.removeProducto(productos.get(pos).getIdProducto());
                JOptionPane.showMessageDialog(this, "El Producto ha sido eliminado de manera satisfactoria!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "<html><h3>¡No ha sido posible eliminar el Producto!</h3></html>", "Error", JOptionPane.ERROR_MESSAGE);
            }
            productos = cargarProductos();
            if (pos == productos.size()) {
                pos--;
            }
            mostrar();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        estado = Estado.CONSULTA;
        mostrar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void ftxCodigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxCodigoBarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxCodigoBarrasActionPerformed

    private void ftxPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxPrecioActionPerformed

    private void ftxStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxStockActionPerformed

    private void txtBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarProductoActionPerformed
        txtBuscarProducto.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                actualizarBúsqueda();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                actualizarBúsqueda();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                actualizarBúsqueda();
            }

            private void actualizarBúsqueda() {
                String texto = txtBuscarProducto.getText();
                productos = servicio.getProductosBusqueda(texto).stream()
                        .filter(p -> p.getAlmacen().getIdAlmacen() == almacen.getIdAlmacen())
                        .toList();;
                busqueda = true;        
                mostrar();        
            }
        });
    }//GEN-LAST:event_txtBuscarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new ProductosAlmacenGestionVista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<Categoria> cbxCategoria;
    private javax.swing.JFormattedTextField ftxCodigoBarras;
    private javax.swing.JFormattedTextField ftxPrecio;
    private javax.swing.JFormattedTextField ftxStock;
    private javax.swing.JScrollPane jspProductos;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigoBarras;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTituloGetock;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMarca;
    // End of variables declaration//GEN-END:variables
    
    private void mostrar() {
        Producto productoSeleccionado = null;

        if (!productos.isEmpty()) {
            productoSeleccionado = productos.get(pos);
        } else if (busqueda) {
            // Vacío
        } else {
            estado = Estado.ALTA;
        }

        if (estado == Estado.ALTA) {
            txtId.setText("| Automático |");
            ftxCodigoBarras.setText("0000000000000");
            txtDescripcion.setText("");
            txtMarca.setText("");
            cbxCategoria.setSelectedIndex(0);
            ftxPrecio.setText("0.01");
            ftxStock.setText("1");
            txtBuscarProducto.setText("");
        } else {
            if (productoSeleccionado != null) {
                txtId.setText(String.valueOf(productoSeleccionado.getIdProducto()));
                ftxCodigoBarras.setText(productoSeleccionado.getCodigoBarras());
                txtDescripcion.setText(productoSeleccionado.getDescripcion());
                txtMarca.setText(productoSeleccionado.getMarca());
                cbxCategoria.setSelectedItem(productoSeleccionado.getCategoria());
                ftxPrecio.setText(String.valueOf(productoSeleccionado.getPrecio()));
                ftxStock.setText(String.valueOf(productoSeleccionado.getStock()));
            }
        }

        btnAñadir.setEnabled(estado == Estado.CONSULTA);
        btnModificar.setEnabled(estado == Estado.CONSULTA);
        btnEliminar.setEnabled(estado == Estado.CONSULTA);
        btnCancelar.setEnabled(estado != Estado.CONSULTA && productos.size() > 0);
        btnGuardar.setEnabled(estado != Estado.CONSULTA);
        txtBuscarProducto.setEnabled(estado == Estado.CONSULTA);

        txtId.setEnabled(false);
        ftxCodigoBarras.setEnabled(estado != Estado.CONSULTA);
        txtDescripcion.setEnabled(estado != Estado.CONSULTA);
        txtMarca.setEnabled(estado != Estado.CONSULTA);
        cbxCategoria.setEnabled(estado != Estado.CONSULTA);
        ftxPrecio.setEnabled(estado != Estado.CONSULTA);
        ftxStock.setEnabled(estado != Estado.CONSULTA);

        actualizandoTabla = true;
        actualizarTabla();
        if (tblProductos.getRowCount() > 0) {
            seleccionarFila(pos);
        }
        actualizandoTabla = false;
    }
    
    private List<Producto> cargarProductos() {
        return servicio.getProductos().stream()
                .filter(p -> p.getAlmacen().getIdAlmacen() == almacen.getIdAlmacen())
                .toList();
    }
    
    private void inicializarTabla() {
        Vector<String> vctTitulosTabla = new Vector<>();
        vctTitulosTabla.add("ID");
        vctTitulosTabla.add("Codigo de Barras");
        vctTitulosTabla.add("Descripción");
        vctTitulosTabla.add("Marca");
        vctTitulosTabla.add("Categoria");
        vctTitulosTabla.add("Precio");
        vctTitulosTabla.add("Stock");

        tblProductos.setDefaultRenderer(Integer.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel lbl = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                lbl.setHorizontalAlignment(JLabel.CENTER);
                lbl.setFont(lbl.getFont().deriveFont(18f));
                return lbl;
            }
        });

        dtm = new DefaultTableModel(vctTitulosTabla, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return switch (columnIndex) {
                    case 0 ->
                        Integer.class;
                    default ->
                        String.class;
                };
            }
        };
        tblProductos.setModel(dtm);
    }

    private void actualizarTabla() {
        dtm.setNumRows(0);
        for (Producto p : productos) {
            Vector vctFila = new Vector();
            vctFila.add(p.getIdProducto());
            vctFila.add(p.getCodigoBarras());
            vctFila.add(p.getDescripcion());
            vctFila.add(p.getMarca());
            vctFila.add(p.getCategoria());
            vctFila.add(p.getPrecio());
            vctFila.add(p.getStock());
            dtm.addRow(vctFila);
        }
    }

    private void cargarComboCategoria() {
        cbxCategoria.removeAllItems();
        for (Categoria cat : Categoria.values()) {
            cbxCategoria.addItem(cat);
        }
        /*String seleccion = (String) cbxCategoria.getSelectedItem();

        if (seleccion != null) {

            Categoria c = Categoria.valueOf(seleccion.toUpperCase());

            switch (c) {
                case Categoria.BEBIDA -> ;
                
                default ->
                    throw new AssertionError();
            }
        }*/

    }

    private void seleccionarFila(int i) {
        if (i >= 0 && i < tblProductos.getRowCount()) {
            tblProductos.setRowSelectionInterval(i, i);
            tblProductos.scrollRectToVisible(tblProductos.getCellRect(i, 0, true));
        }
    }

    
}
