/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.daw1.aplicaciontorneo.vista;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.CardLayout;
import org.zabalburu.daw1.aplicaciontorneo.vista.paneles.PnlDashboard;
import org.zabalburu.daw1.aplicaciontorneo.vista.paneles.PnlJuegos;
import org.zabalburu.daw1.aplicaciontorneo.vista.paneles.PnlJugadores;

/**
 *
 * @author DAW1
 */
public class FrmTorneo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmTorneo.class.getName());

    /**
     * Creates new form FrmTorneo
     */
    public FrmTorneo() {
        initComponents();
        pnlPrincipal.add(new PnlDashboard(),"DASHBOARD");
        pnlPrincipal.add(new PnlJuegos(), "JUEGOS");
        pnlPrincipal.add(new PnlJugadores(), "JUGADORES");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrOpciones = new javax.swing.ButtonGroup();
        pnlAcciones = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        lblCampeonato = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        tbtDashboard = new javax.swing.JToggleButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        tbtJuegos = new javax.swing.JToggleButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        tbtJugadores = new javax.swing.JToggleButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        tbtPartidas = new javax.swing.JToggleButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        tbtRegistrar = new javax.swing.JToggleButton();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Campeonato PC Games");

        pnlAcciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlAcciones.setLayout(new javax.swing.BoxLayout(pnlAcciones, javax.swing.BoxLayout.Y_AXIS));
        pnlAcciones.add(filler2);

        lblCampeonato.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lblCampeonato.setText("🏆 CAMPEONATO");
        lblCampeonato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlAcciones.add(lblCampeonato);
        pnlAcciones.add(filler1);

        bgrOpciones.add(tbtDashboard);
        tbtDashboard.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        tbtDashboard.setText("Dashboard");
        tbtDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtDashboard.setMaximumSize(new java.awt.Dimension(160, 35));
        tbtDashboard.setMinimumSize(new java.awt.Dimension(160, 35));
        tbtDashboard.setPreferredSize(new java.awt.Dimension(160, 35));
        tbtDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtDashboardActionPerformed(evt);
            }
        });
        pnlAcciones.add(tbtDashboard);
        pnlAcciones.add(filler3);

        bgrOpciones.add(tbtJuegos);
        tbtJuegos.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        tbtJuegos.setText("Juegos");
        tbtJuegos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtJuegos.setMaximumSize(new java.awt.Dimension(160, 35));
        tbtJuegos.setMinimumSize(new java.awt.Dimension(160, 35));
        tbtJuegos.setPreferredSize(new java.awt.Dimension(160, 35));
        tbtJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtJuegosActionPerformed(evt);
            }
        });
        pnlAcciones.add(tbtJuegos);
        pnlAcciones.add(filler4);

        bgrOpciones.add(tbtJugadores);
        tbtJugadores.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        tbtJugadores.setText("Jugadores");
        tbtJugadores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtJugadores.setMaximumSize(new java.awt.Dimension(160, 35));
        tbtJugadores.setMinimumSize(new java.awt.Dimension(160, 35));
        tbtJugadores.setPreferredSize(new java.awt.Dimension(160, 35));
        tbtJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtJugadoresActionPerformed(evt);
            }
        });
        pnlAcciones.add(tbtJugadores);
        pnlAcciones.add(filler5);

        bgrOpciones.add(tbtPartidas);
        tbtPartidas.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        tbtPartidas.setText("Partidas");
        tbtPartidas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtPartidas.setMaximumSize(new java.awt.Dimension(160, 35));
        tbtPartidas.setMinimumSize(new java.awt.Dimension(160, 35));
        tbtPartidas.setPreferredSize(new java.awt.Dimension(160, 35));
        pnlAcciones.add(tbtPartidas);
        pnlAcciones.add(filler6);

        bgrOpciones.add(tbtRegistrar);
        tbtRegistrar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        tbtRegistrar.setText("Registrar");
        tbtRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbtRegistrar.setMaximumSize(new java.awt.Dimension(160, 35));
        tbtRegistrar.setMinimumSize(new java.awt.Dimension(160, 35));
        tbtRegistrar.setPreferredSize(new java.awt.Dimension(160, 35));
        pnlAcciones.add(tbtRegistrar);

        getContentPane().add(pnlAcciones, java.awt.BorderLayout.LINE_START);

        pnlPrincipal.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1265, 522));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbtDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtDashboardActionPerformed
        cambiarPanel("DASHBOARD");
    }//GEN-LAST:event_tbtDashboardActionPerformed

    private void tbtJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtJuegosActionPerformed
        cambiarPanel("JUEGOS");
    }//GEN-LAST:event_tbtJuegosActionPerformed

    private void tbtJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtJugadoresActionPerformed
         cambiarPanel("JUGADORES");
    }//GEN-LAST:event_tbtJugadoresActionPerformed

    private void cambiarPanel(String nombre) {
        CardLayout cl = (CardLayout) pnlPrincipal.getLayout();
        cl.show(pnlPrincipal, nombre);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLaf.setup(new FlatMacLightLaf());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmTorneo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrOpciones;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel lblCampeonato;
    private javax.swing.JPanel pnlAcciones;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JToggleButton tbtDashboard;
    private javax.swing.JToggleButton tbtJuegos;
    private javax.swing.JToggleButton tbtJugadores;
    private javax.swing.JToggleButton tbtPartidas;
    private javax.swing.JToggleButton tbtRegistrar;
    // End of variables declaration//GEN-END:variables
}
